import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import { execFileSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
execFileSync(process.execPath, [path.join(root, 'scripts', 'build.mjs')], { stdio: 'inherit' });
const buildSource = fs.readFileSync(path.join(root, 'scripts', 'build.mjs'), 'utf8');
if (!buildSource.includes("'process.release.name': '\"browser\"'")) throw new Error('Obsidian renderer must use the browser inference runtime');

const manifest = JSON.parse(fs.readFileSync(path.join(root, 'manifest.json'), 'utf8'));
if (manifest.id !== 'gib-search') throw new Error('manifest id must be gib-search');
if (manifest.name !== 'Gib Search') throw new Error('manifest name must be Gib Search');
if (!/^0\.\d+\.\d+$/.test(manifest.version)) throw new Error('public beta versions must remain in 0.x.x');
if (manifest.isDesktopOnly) throw new Error('Gib Search must remain available on mobile');

const builtMain = fs.readFileSync(path.join(root, 'main.js'), 'utf8');
const runtimeSource = fs.readFileSync(path.join(root, 'src', 'mobile-runtime.js'), 'utf8'); const semanticSource = runtimeSource.slice(runtimeSource.indexOf('async semanticHighlights('), runtimeSource.indexOf('cacheResult(', runtimeSource.indexOf('async semanticHighlights(')));
const mainSource = fs.readFileSync(path.join(root, 'src', 'main.js'), 'utf8'), workerSource = fs.readFileSync(path.join(root, 'src', 'desktop-embed-worker.js'), 'utf8'); const modalSource = mainSource.slice(mainSource.indexOf('class SemanticSearchModal'), mainSource.indexOf('class SemanticInNoteSearch')), physicsSource = mainSource.slice(mainSource.indexOf('physicsStep(alpha)'), mainSource.indexOf('startSimulation(', mainSource.indexOf('physicsStep(alpha)')));
const mobileRuntimeSource = fs.readFileSync(path.join(root, 'src', 'mobile-runtime.js'), 'utf8');
const embeddedWasm = builtMain.match(/EMBEDDED_WASM_GZIP\s*=\s*["']([^"']+)["']/);
if (!embeddedWasm) throw new Error('main.js does not contain the bundled WebAssembly runtime');
const embeddedWasmModule = builtMain.match(/EMBEDDED_WASM_MODULE_GZIP\s*=\s*["']([^"']+)["']/);
if (!embeddedWasmModule) throw new Error('main.js does not contain the bundled WebAssembly loader');
const bundledBinary = zlib.gunzipSync(Buffer.from(embeddedWasm[1], 'base64'));
const bundledModule = zlib.gunzipSync(Buffer.from(embeddedWasmModule[1], 'base64')).toString('utf8');
const sourceBinary = fs.readFileSync(path.join(root, 'node_modules', '@huggingface', 'transformers', 'dist', 'ort-wasm-simd-threaded.jsep.wasm'));
if (!bundledBinary.equals(sourceBinary)) throw new Error('Bundled WebAssembly runtime differs from the pinned dependency');
if (!bundledModule.includes('n=false') || !bundledModule.includes('var isNode = false;')) throw new Error('Bundled WebAssembly loader can still select Node worker modules');
if (!bundledModule.includes('Xa??="embedded.wasm"')) throw new Error('Bundled WebAssembly loader still depends on its module URL');
if (!builtMain.includes('wasmBinary = this.plugin.embeddedWasmBinary')) throw new Error('Bundled WebAssembly runtime is not connected to inference');
if (!builtMain.includes('wasmPaths = { mjs: this.plugin.embeddedWasmModuleUrl }')) throw new Error('Bundled WebAssembly loader is not connected to inference');
if (!builtMain.includes('new window.Worker')) throw new Error('Desktop inference is not isolated in a browser worker');
if (!builtMain.includes('web-worker-wasm')) throw new Error('Desktop worker health reporting is missing');
if (builtMain.includes("require('node:worker_threads')") || builtMain.includes("require('node:child_process')") || builtMain.includes('ELECTRON_RUN_AS_NODE')) throw new Error('Unsupported Node background runtime is still bundled');
if (!builtMain.includes('embedQueue = embedQueue.then')) throw new Error('Desktop inference requests are not serialized');
if (!builtMain.includes('index.highlights.bin') || !builtMain.includes('highlightCandidates') || !builtMain.includes('packedHighlightVectors')) throw new Error('Precomputed semantic highlight index is missing');
if (builtMain.includes('cachedPassageVectors')) throw new Error('Search-time phrase embedding is still bundled');
if (/embedBatch|initializeModel|cachedPassageVectors/.test(semanticSource)) throw new Error('Semantic highlighting still performs search-time inference');
if (!builtMain.includes('contentFingerprint(content)') || !builtMain.includes('sameChunks(previous')) throw new Error('Index change detection still depends only on file timestamps');
if (!builtMain.includes('this.plugin.app.vault.read(file)')) throw new Error('Index verification still uses potentially stale cached vault reads');
if (!builtMain.includes('Index pair is incomplete') || !builtMain.includes('attempt < 40')) throw new Error('Desktop index loading does not retry transient sync races');
if (builtMain.includes('if (!existingDirectory) return undefined')) throw new Error('Desktop index loading skips retries when sync temporarily removes the index directory');
if (!builtMain.includes("if (!this.isMobile) throw error")) throw new Error('Desktop index load failures can still trigger an empty rebuild');
if (!builtMain.includes('retainedMeta.push') || builtMain.includes('const remove = new Set([...changed.map')) throw new Error('Index refresh can still discard changed files before their replacements are ready');
if (!builtMain.includes('waitForVaultSettled') || !builtMain.includes('Waiting for the vault to finish loading')) throw new Error('Startup can still scan a partial Obsidian vault');
if (builtMain.includes('this.highlightTimer') || builtMain.includes('quickLimit = Math.min(4')) throw new Error('Search results still render before semantic highlighting finishes');
if (!builtMain.includes('semanticHighlights: tweaks.semanticHighlights')) throw new Error('Semantic highlighting is not part of the initial result render');
if (builtMain.includes("if (!this.vectors.length) throw new Error(this.message || 'The semantic index is not ready'); await this.initializeModel()")) throw new Error('Desktop search still warms BGE on the UI thread');
if (!builtMain.includes('searchLive(query')) throw new Error('Live semantic query scheduling is missing');
if (!runtimeSource.includes('correctQuery(query)') || !runtimeSource.includes('editDistanceWithin(lower, candidate, 1)') || !runtimeSource.includes('queryVector(correctedQuery)')) throw new Error('Vault-derived typo-tolerant semantic queries are missing');
if (!builtMain.includes('SemanticMapCanvas') || !builtMain.includes('Open note neighborhood') || !builtMain.includes('Explore from note')) throw new Error('Semantic search map or note neighborhood UI is missing');
if (!builtMain.includes('semanticQueryMap(query, files)') || !builtMain.includes('semanticStarfield(query, files = null, focusFiles = [])') || !builtMain.includes('semanticNeighbors(file')) throw new Error('Local semantic map data is missing');
if (!builtMain.includes('LivingSemanticMapCanvas') || !builtMain.includes('graph.edges || []')) throw new Error('Living semantic force map or note gravity is missing');
if (!modalSource.includes('new LivingSemanticMapCanvas') || modalSource.includes('this.map = new SemanticMapCanvas')) throw new Error('Search modal is not using the living semantic force map');
if (!mainSource.includes('distance < closestDistance') || !modalSource.includes('wasSelected !== isSelected') || !modalSource.includes('attributeOldValue: true')) throw new Error('Graph hover can select an overlapping or stale result instead of the pointed node');
if (!mainSource.includes('this.startSimulation(previous.size ? .82 : 1)') || !mainSource.includes("id: '__query__'") || !mainSource.includes("const strength = .012 * (querySettling ? Math.max(alpha, .28) : alpha)")) throw new Error('Persistent animated query target is missing');
if (!mainSource.includes('async function buildQueryMapModel(') || (mainSource.match(/buildQueryMapModel\(this\.plugin, query, results/g) || []).length < 2) throw new Error('Modal and dedicated maps do not share the canonical query model');
if (!mainSource.includes('idlePhysicsStep(now)') || !mainSource.includes('const topicNodes = querySettling ? foreground : activeNodes')) throw new Error('Query maps can freeze after settling or receive background topic forces');
if (!mainSource.includes('points = new Map(visible.map(node => { const [x, y] = this.baseCoordinates(node') || !mainSource.includes('this.baseCoordinates(this.queryNode, width, height)') || mainSource.includes('canonicalTerrain = this.hasQuery')) throw new Error('Query terrain is not following live physical node positions before projection');
if (!mainSource.includes('plugin.queryMapCache') || !runtimeSource.includes('this.conceptFacetCache = new Map()') || !runtimeSource.includes('if (i % 192 === 191) { await yieldToUi()') || !runtimeSource.includes('if (first % 6 === 5) await yieldToUi()')) throw new Error('Query-model caching or cooperative search scheduling is missing');
if (/buildSemanticHeatField|triangulateTerrain|quadraticCurveTo/.test(mainSource)) throw new Error('Obsolete decorative terrain rendering remains in the semantic map');
if (!mainSource.includes('semanticDensityField(width, height)') || !mainSource.includes('generationWeight') || !mainSource.includes('!edge.crossCommunity && edge.strength > .14') || !mainSource.includes('vaultTerrain ? [.16, .32, .48, .64, .8, .92] : [.35, .62, .95, 1.35, 1.9, 2.6]') || !mainSource.includes('traceDensityLevel(ctx, field, level)')) throw new Error('Semantic-support density, bounded relationship ridges, or fixed contour elevations are missing');
if (!mainSource.includes('manualRoadEdges(app, files)') || !mainSource.includes('metadataCache?.resolvedLinks') || !mainSource.includes('setGraph(center, values, edges = [], roads = [])')) throw new Error('Manual wikilink road data is missing');
if (!mainSource.includes('paintSweepLinks(ctx, width, height, colors)') || !mainSource.includes('this.paintSweepLinks(ctx, rect.width, rect.height, colors)') || !mainSource.includes('ctx.bezierCurveTo(controlOne.x')) throw new Error('Smooth cubic manual-link sweeps are missing');
if (!mainSource.includes('addGuide = (id, x, y)') || !mainSource.includes('fallbackX * .76 + guide.x / length * .24') || !mainSource.includes('handle = Math.max(14, Math.min(68')) throw new Error('Stable endpoint bundling or restrained sweep geometry is missing');
if (/routeRoad\(|depositRoadTraffic|beginRoadRouteRefresh|paintRoads\(/.test(mainSource)) throw new Error('Obsolete terrain pathfinding road code remains');
if (!mainSource.includes('(now - introduced) / 140') || !mainSource.includes('this.roadAnimationFrame = requestAnimationFrame')) throw new Error('Quiet whole-link fade animation is missing');
if (!mainSource.includes('manualRoadEdges(plugin.app, nodes.map(node => node.id))') || !mainSource.includes('manualRoadEdges(this.app, [file.path, ...nodes.map(node => node.id)])')) throw new Error('Search or local-note maps are not receiving manual link roads');
if (!mainSource.includes('graphManualLinkInfluence: true') || !mainSource.includes('gib-search-map-link-lines') || !mainSource.includes('setShowLinks(value') || !mainSource.includes('if (!this.showLinks || !this.roadEdges.length)') || !mainSource.includes('showLinks: this.plugin.settings.showWikilinks') || !mainSource.includes('gib-search-map-link-influence') || !mainSource.includes('setManualLinkInfluence(value') || !mainSource.includes('this.roadDegrees = roadDegrees') || !physicsSource.includes("this.manualLinkInfluence && this.mapGroupingMode !== 'links'") || !physicsSource.includes('hubScale = 1 / Math.sqrt') || !physicsSource.includes('Math.tanh((distance - desired) * 3.2)')) throw new Error('Independent map-level manual-link visibility and physics toggles are missing');
if (!mainSource.includes('node.matched && node.generation === 1') || !mainSource.includes('addRidge(center, target') || !mainSource.includes('(supportMaximum * 1.18 + .42) * this.queryPresence')) throw new Error('Query or local-note terrain summit and direct-result ridges are missing');
if (!mainSource.includes('suppressEmptySummits(values, columns, rows, step, anchors, sigma)') || !mainSource.includes('height - (Number(nearest.anchor.height) - .008)') || !mainSource.includes('values[row * columns + column] += amplitude * gaussian') || !mainSource.includes('rawGuard * rawGuard * (3 - 2 * rawGuard)') || !mainSource.includes('values[index] - depression[index]')) throw new Error('Additive terrain or guarded off-node summit correction is missing');
if (mainSource.includes('anchorSummitMesas(') || mainSource.includes('summit: summit * .985')) throw new Error('Node-centered terrain mesas still create artificial nodules');
if (!mainSource.includes('step = 5') || !mainSource.includes('Math.sqrt(48 / Math.max(1, visible.length))') || !mainSource.includes('27 * zoom * vaultDensityScale') || !mainSource.includes('addHeight = (x, y, radius, visibility, uniqueness)') || !mainSource.includes('heightTotals[index] / weight * (1 - Math.exp(-weight * 4))') || !mainSource.includes('vaultTerrain ? [.16, .32, .48, .64, .8, .92]') || !mainSource.includes('if (!vaultTerrain) this.suppressEmptySummits') || !mainSource.includes('this.gaussianLookup') || !mainSource.includes('refreshInterval') || !mainSource.includes("terrainContext.lineJoin = 'round'")) throw new Error('High-resolution, uniqueness-weighted, zoom-stable terrain rendering is missing');
if (!mainSource.includes('if (this.center?.id) labels.push({ node: this.queryNode') || mainSource.includes("'Search origin'") || !mainSource.includes('ctx.lineTo(queryX + marker * .72, queryY)') || !mainSource.includes('this.queryMarkerFocus * 1.2') || !mainSource.includes('Number(b.query) - Number(a.query)') || !mainSource.includes('chosen.leader')) throw new Error('Query labels remain visible or cartographic map labels are incomplete');
if (!mainSource.includes('now - Number(this.lastTerrainAt || 0) >= refreshInterval') || !mainSource.includes('this.terrainMask')) throw new Error('Semantic terrain is not cached at the smooth animation cadence');
if (mainSource.includes('node.matched && (node.accent > .01 || active)') || !mainSource.includes('if (focused && !queryFocused) labelNodes.add(focused)')) throw new Error('Result rings or always-visible map labels remain');
if (!mainSource.includes('this.byId.get(this.hovered) || this.byId.get(this.selected)') || !mainSource.includes('this.hovered = id; this.updateDetail();')) throw new Error('Map detail is not limited to hovered or selected results');
if (!mainSource.includes('collisionDistance(a, b') || !mainSource.includes('resolveLayoutOverlaps(this.nodes, hasQuery)') || !mainSource.includes('applyCollisionForces(bodies, alpha)') || !mainSource.includes('cellSize = .09') || !mainSource.includes('[query, ...activeNodes]') || !mainSource.includes('a.matched && !b.matched') || !mainSource.includes('promoted = Boolean(hasQuery && matched && old && !old.matched)') || !mainSource.includes('captureBoost = node.matched ? Number(node.capture || 0) * .032')) throw new Error('Calculated-layout capture or collision-safe node placement is missing');
if (!mainSource.includes('Finding places for ${files.length} notes…') || !mainSource.includes('Math.sqrt((index + .5) / count) * .16')) throw new Error('Visible vault-map startup assembly is missing');
if (!mainSource.includes('relationship = focused && !queryFocused') || !mainSource.includes('.18 + related * .76')) throw new Error('Line-free semantic hover emphasis is missing');
if (!runtimeSource.includes('louvainCommunities(ids, edges, resolution = 1)') || !runtimeSource.includes('mergeConnectedCommunities(ids, edges, communities, maximum)') || !runtimeSource.includes('Math.ceil(ids.length / maximum * 2.1)') || !runtimeSource.includes('pair.maximum * .7 + pair.sum / pair.count * .3') || !runtimeSource.includes('const reverse = directed[second].get(first)') || !runtimeSource.includes('vaultContentProfiles(requested)') || !runtimeSource.includes('contentProfileSimilarity(profiles.get(entries[first].id)') || !runtimeSource.includes("vaultMode ? 'chunks' : 'files'") || !runtimeSource.includes('vaultMode ? mergeConnectedCommunities') || !runtimeSource.includes('weights.community * community ** 2')) throw new Error('Distinctive multi-passage communities are not represented in the combined distance model');
if (!runtimeSource.includes('locallyDistinctAffinityMatrix(scores)') || !runtimeSource.includes('specificTermProfiles(files = null)') || !runtimeSource.includes('specificTermSimilarity(termProfiles.get') || !runtimeSource.includes('Math.sqrt(directed[first][second] * directed[second][first]) * .8') || !runtimeSource.includes('1 - localContentAffinities[first][second]')) throw new Error('Vault topology is missing mutual local distinctiveness or rare-term evidence');
if (!mainSource.includes('if (!linkMode) { const corralBodies') || !mainSource.includes('distance <= .92') || !mainSource.includes('(distance - .92) * .045') || !physicsSource.includes('Number(tuning.neighborAttraction) > 0') || physicsSource.includes('edge.residual')) throw new Error('Tunable physics or non-Link emergency corralling is missing');
if (!mainSource.includes('MAP_TUNING_DEFAULTS') || !mainSource.includes('MAP_TUNING_CONTROLS') || !mainSource.includes('setupTuningPanel()') || !mainSource.includes("text: 'Reset'") || !mainSource.includes('this.settings.mapTuning = Object.assign') || !mainSource.includes('showTopography: true') || !mainSource.includes("key: 'showTopography'") || !mainSource.includes('this.tuning?.showTopography === false') || !mainSource.includes('terrainSpread') || !mainSource.includes('terrainContrast') || !mainSource.includes('collisionSpacing') || !physicsSource.includes('anchorStrength')) throw new Error('Live, persistent vault map tuning or topography controls are missing');
if (!mainSource.includes('class SemanticMapWebGLRenderer') || !mainSource.includes("getContext('webgl2'") || !mainSource.includes("powerPreference: 'high-performance'") || !mainSource.includes('buildTerrainMesh(1)') || !mainSource.includes('map.webglError') || !mainSource.includes('webglcontextlost') || !mainSource.includes('this.webglRenderer?.destroy()') || !mainSource.includes('delete this.settings.mapProjection') || mainSource.includes('validMapProjection') || mainSource.includes('projectScreen(x, y, width, height)') || mainSource.includes('u_projection') || mainSource.includes('2.5D')) throw new Error('Flat WebGL rendering, visible Canvas fallback diagnostics, or removal of the experimental projection path is incomplete');
if (!fs.readFileSync(path.join(root, 'styles.css'), 'utf8').includes('.gib-search-map-gl{position:absolute')) throw new Error('WebGL map layer styling is missing');
if (!runtimeSource.includes('commonnessSuppression') || !runtimeSource.includes('passageDiversity') || !runtimeSource.includes('passageCoverage') || !runtimeSource.includes('distanceContrast') || !runtimeSource.includes('contentWeight') || !runtimeSource.includes('residualWeight')) throw new Error('Vault similarity tuning is not wired into the distance model');
if (!mainSource.includes("mapGroupingMode: 'similarity'") || !mainSource.includes('setupMapModeControl()') || !mainSource.includes("['similarity', 'topics', 'links']") || !mainSource.includes('mapMode: this.mapGroupingMode') || !mainSource.includes("setName('Default map grouping')") || !runtimeSource.includes("topicMode = options.mapMode === 'topics'") || !runtimeSource.includes('topicAffinities.set(entry.id') || !runtimeSource.includes('community: .6') || !mainSource.includes('result?.conceptAffinities || node.topicAffinities')) throw new Error('Persistent topical map grouping with soft bridge-note membership is missing');
if (!mainSource.includes("linkMode = this.mapGroupingMode === 'links'") || !mainSource.includes('prepareLinkComponents()') || !mainSource.includes('this.prepareLinkComponents()') || !mainSource.includes('applyLinkGraphForces(nodes, alpha)') || !mainSource.includes('if (linkMode) this.applyLinkGraphForces(linkNodes, alpha)') || !mainSource.includes('const temperature = Math.max(.22, alpha)') || !mainSource.includes('desired = .2 + (source.fileScale + target.fileScale) * .03') || !mainSource.includes('.000032 / (distanceSquared + .0035)') || !mainSource.includes('linkNodeIds?.has(node.id) ? 0') || !mainSource.includes('relaxationNodes = linkMode ? []') || !mainSource.includes('vaultMode && !linkMode') || !mainSource.includes('targetZoom = linkMode ?') || !mainSource.includes('linkStableFrames') || !mainSource.includes('linkSimulationTicks') || !mainSource.includes("addOption('links', 'Links')") || !mainSource.includes("this.linkInfluenceButton.disabled = integrated") || runtimeSource.includes('weights.link * linkDistance ** 2') || runtimeSource.includes('linkCount = Number(resolvedLinks')) throw new Error('Isolated, stability-cooled force-directed Links mode is missing or still mixed into semantic reduction');
if (!mainSource.includes('paintTopicCommunities(ctx') || !mainSource.includes('topicCommunityGroups(width, height)') || !mainSource.includes('communityBoundaryField(points, padding, connect = true)') || !mainSource.includes('communityCoreIslands(values, padding)') || !mainSource.includes('this.hasQuery ? [group.values] : this.communityCoreIslands') || !mainSource.includes('this.communityCanvas') || !mainSource.includes('drawCommunityLabels(ctx') || !mainSource.includes('.filter(group => group.label)') || !mainSource.includes('displayTopicHue') || !mainSource.includes('boundaryRepulsionEnabled') || !mainSource.includes("label: 'Community sensitivity'") || !mainSource.includes("label: 'Membership threshold'") || !mainSource.includes("label: 'Repel outsiders'") || !runtimeSource.includes('topicCommunityLabels(entries, communities') || !runtimeSource.includes('structuralSpeakerLabels') || !runtimeSource.includes('isTemporalConceptLabel') || !runtimeSource.includes("candidate.field === 'filename'") || !runtimeSource.includes('fallbackLabel') || !runtimeSource.includes('scale * degree[node] * totals[current]')) throw new Error('Context-aware topical territories, grounded labels, distinct colors, sensitivity, or outsider repulsion are missing');
if (!runtimeSource.includes('querySubtopicCoordinates(entries, topics, nodeById)') || !runtimeSource.includes('layoutTopics = topicMode && !vaultCentered') || !mainSource.includes('facets = await plugin.search.conceptFacets(query, activeFiles)')) throw new Error('Query-relative subtopic sectors are missing from Topic mode');
if (!mainSource.includes('this.resultsCollapsed = true') || mainSource.includes('this.setResultsCollapsed(false); this.resultList.empty()') || !mainSource.includes('if (item && !this.resultsCollapsed)')) throw new Error('Dedicated-map results panel does not preserve its collapsed state');
if (!mainSource.includes("MarkdownRenderer.render(this.app, source, this.previewBody") || !mainSource.includes("onSelect: file => this.showPreview(file)") || !mainSource.includes('gib-graph-preview-panel') || !fs.readFileSync(path.join(root, 'styles.css'), 'utf8').includes('.gib-graph-preview-panel')) throw new Error('Dedicated-map note preview panel is missing');
if (!mainSource.includes('backgroundEdges = this.baseEdges.filter') || !physicsSource.includes('preserveBackground && querySettling') || !mainSource.includes('elapsed * .0000028 + Math.sin') || !mainSource.includes('idlePhysicsStep(now)') || !mainSource.includes('this.applyCollisionForces(this.queryPresence > .04 ? [this.queryNode, ...activeNodes] : activeNodes, .12)') || !mainSource.includes('if (activePhysics) this.physicsStep') || !mainSource.includes('else this.idlePhysicsStep(now)') || !mainSource.includes('this.ambientPosition(node.x, node.y, false, node.id)') || !mainSource.includes('this.ambientPosition(viewX, viewY, true, this.dragging.id)') || !mainSource.includes('this.pendingQuery ? 120 : this.ambientDrawing ? 180 : 48')) throw new Error('Continuous collision-safe whole-map motion or its performance guard is missing');
if (!modalSource.includes('results = this.lastResults.slice(0, 80)') || !mainSource.includes('semanticStarfield(query, activeFiles, activeFiles)') || !mainSource.includes('.08 + rankedRelevance * .92')) throw new Error('Query map is not scoped to visible results or using the full relevance range');
if (!runtimeSource.includes('semanticTopicBasis(entries)') || !runtimeSource.includes('topicCoordinates(entries, queryVector, basis.axes)') || !runtimeSource.includes('angular ** 2') || !mainSource.includes('node.topicHue')) throw new Error('Stable topic compass coordinates, distance contribution, or semantic hues are missing');
if (!runtimeSource.includes('extractGraphEntities(source)') || !runtimeSource.includes('entityAffinity =') || !runtimeSource.includes('entityBoost')) throw new Error('Entity-aware indexing, graph neighborhoods, or reranking is missing');
if (!runtimeSource.includes("RELATION_MODEL_ID = 'Xenova/mobilebert-uncased-mnli'") || !runtimeSource.includes('graphRelationships(edges, budget') || !modalSource.includes('argumentCandidateEdges(candidates.map') || !mainSource.includes('graphRelationshipBudgetMobile')) throw new Error('Budgeted local relationship intelligence is missing');
if (!builtMain.includes('index.relationships.json') || !runtimeSource.includes('saveRelationCache()') || !runtimeSource.includes('missing.length < maximum')) throw new Error('Relationship inference is not persistently cached or bounded');
if (workerSource.includes("message.type === 'relations') embedQueue") || !modalSource.includes('window.setTimeout(resolve, 180)') || !modalSource.includes('version !== this.lensVersion')) throw new Error('Relationship intelligence can block or outrun live search input');
if (!mainSource.includes('generatedTopicLabels: true') || !mainSource.includes('Generated topic labels') || !mainSource.includes('index.topic-labels.json') || !workerSource.includes("Xenova/flan-t5-base") || !workerSource.includes("message.type === 'topic-labels'") || !mobileRuntimeSource.includes('generatedTopicCommunityLabels') || !mobileRuntimeSource.includes('Select the single best topic label from this list') || !mobileRuntimeSource.includes('vaultCoverage') || !mobileRuntimeSource.includes(':v3:') || !mobileRuntimeSource.includes('saveTopicLabelCache')) throw new Error('Grounded, cached local topic labels are missing');
if (!mainSource.includes('Cached topic labels') || !mainSource.includes('Topic labeler') || !mainSource.includes('Topic labels:') || !mobileRuntimeSource.includes('modelActivity') || !mobileRuntimeSource.includes('modelReady')) throw new Error('Model and topic-label health status is ambiguous');
if (!mainSource.includes('this.hasQuery && !this.pendingQuery ? foreground : this.nodes') || !mainSource.includes('this.pendingQuery') || !mainSource.includes('this.cameraZoom')) throw new Error('Calculated foreground isolation, pending-query transition, or zoom is missing');
if (mainSource.includes('parallaxX') || mainSource.includes('ctx.filter') || !mainSource.includes('radius + 2.2 * blur') || !mainSource.includes('opacity * (1 - blur * .28)')) throw new Error('Efficient dedicated-view background fade or soft-focus treatment is incomplete');
if (!mainSource.includes("getDisplayText() { return 'Gib Search map'; }") || !mainSource.includes('preserveBackground: true') || !mainSource.includes('query.length < 3') || !mainSource.includes('this.map.beginQuery(query, true)') || !mainSource.includes('const repellers = this.pendingQuery ? [query] : [query, ...foreground]') || !mainSource.includes('merged = this.baseNodes.map') || !mainSource.includes('gib-graph-results-panel') || !mainSource.includes('setResultsCollapsed(value)')) throw new Error('Dedicated living vault map, three-character query transition, background repulsion, or floating results panel is missing');
if (mainSource.includes('class LegacyGraphView') || mainSource.includes('loadGraph()') || mainSource.includes('Highlight by meaning') || mainSource.includes('gib-graph-canvas')) throw new Error('Legacy semantic graph implementation remains bundled');
if (!runtimeSource.includes('semanticGenerations(seedFiles') || !modalSource.includes('searchMapGenerations') || !mainSource.includes('gib-search-map-generations')) throw new Error('On-map semantic generation controls are missing');
if (!mainSource.includes("addEventListener('wheel'") || !mainSource.includes('this.panning =') || !mainSource.includes('this.pinch =') || !mainSource.includes('setUserZoom(value') || !mainSource.includes('resetViewport()') || !mainSource.includes('this.panX')) throw new Error('Graph pan, cursor-centered zoom, pinch zoom, or fit controls are missing');
if (!runtimeSource.includes('residualVector(entry.vector, queryVector)')) throw new Error('Search-map grouping still includes the shared query direction');
if (!runtimeSource.includes('multiRelationalLayout(query, nodes') || !runtimeSource.includes('vaultCentered = Boolean(options.vaultCenter)') || !runtimeSource.includes('Float32Array.from(basis.center)') || !runtimeSource.includes('contentWeight: .72') || !runtimeSource.includes('vaultCentered && point ? { x: point.x, y: point.y }') || !runtimeSource.includes('classicalDistanceLayout(ids, distances, conditioned ? layoutTopics : topics)') || !runtimeSource.includes('weights.content * content ** 2') || !runtimeSource.includes('relationDistance ** 2') || !modalSource.includes('vaultCenter: true')) throw new Error('Vault-centroid content-distribution positioning or query-conditioned reduction is incomplete');
if (!runtimeSource.includes('passage.commonness =') || !runtimeSource.includes('passage.weight = 1 - suppression * index / divisor') || !runtimeSource.includes('a.weight * (1 - diversityWeight) + diversity(a) * diversityWeight') || !runtimeSource.includes('coverage * blend + peak * (1 - blend)') || !runtimeSource.includes('this.contentProfileCache = null')) throw new Error('Vault-relative passage weighting, facet diversity, or profile cache invalidation is incomplete');
if (runtimeSource.includes('topChunkSimilarity(') || runtimeSource.includes('filePassageVectors(')) throw new Error('The superseded strongest-chunk vault comparison is still bundled');
if (runtimeSource.includes('vaultThresholdLayout') || runtimeSource.includes('adaptiveVaultPositions') || runtimeSource.includes('upper + (ceiling - upper) * .62') || runtimeSource.includes('thresholdEdges') || runtimeSource.includes('desired = .045 + (1 - affinity) * .13')) throw new Error('A superseded vault positioning experiment is still active');
if (!mainSource.includes("defaultSearchLens: 'relevance'") || !mainSource.includes('SEARCH_LENSES') || !modalSource.includes('applyLens()') || !modalSource.includes('gib-search-lens-select')) throw new Error('Coordinated search lenses or the Relevance default are missing');
if (!runtimeSource.includes('async conceptFacets(query, files)') || !runtimeSource.includes('contextScores(files)') || !runtimeSource.includes('argumentCandidateEdges(files)') || !modalSource.includes("lens === 'arguments'")) throw new Error('Concept, context, or argument lens analysis is missing');
if (!modalSource.includes("lens === 'relevance'") || !modalSource.includes('conceptAffinities') || modalSource.includes("lens === 'concepts'")) throw new Error('Concept structure is not integrated into relevance or the obsolete Concepts lens remains');
if (!runtimeSource.includes("conditioned ? ['__center__'") || !runtimeSource.includes('generation || 1) > 1') || !runtimeSource.includes('parent = positioned.get(node?.parent)')) throw new Error('Centerless vault layout or parent-relative semantic generations are missing');
if (!runtimeSource.includes('centeredVectorCloud(rawConceptEntries, primaryRawConcepts)') || !runtimeSource.includes('positioned.set(entry.id, vaultCentered && point') || !runtimeSource.includes('Math.cos(angle) * radius')) throw new Error('Search and vault positions are not using their dedicated semantic layouts');
if (!runtimeSource.includes('indexedConceptCandidates(queryVector') || !runtimeSource.includes('centrality * .35 + memberCoverage * .22 + distinction * .18') || !runtimeSource.includes('vaultCoverage') || !runtimeSource.includes("label: confidence >= .4")) throw new Error('Cluster labels are not grounded, centroid-ranked, rarity-weighted, and confidence-gated');
if (modalSource.includes("lensLabel = result === anchor ? 'Anchor'") || modalSource.includes('source.slice(1,') || !modalSource.includes("result.lensLabel = 'Position'") || !modalSource.includes('Comparing positions')) throw new Error('Argument analysis is still anchored to the first search result');
if (!runtimeSource.includes('evidence-v1') || !runtimeSource.includes('evidence: item.evidence') || !modalSource.includes('argumentEvidenceText(candidateByFile.get') || !modalSource.includes('gib-semantic-argument-compared')) throw new Error('Argument cards do not preserve and render auditable passage evidence');
if (!mainSource.includes("class NeighborhoodView") || !mainSource.includes("'aria-label': 'Local note lens'") || !mainSource.includes('centerFile: file.path') || !mainSource.includes('conceptFacetsFromFile(file.path')) throw new Error('Local-note lenses are not conditioned on the active note');
if (mainSource.includes('residual: support ?') || physicsSource.includes('relation')) throw new Error('Relationship judgments are still applied as independent graph forces');
if (!physicsSource.includes('this.applyCollisionForces(') || !physicsSource.includes('Number(tuning.repulsion || 0) * alpha') || !mainSource.includes('repulsion: 0')) throw new Error('Vault physics no longer defaults to collision-safe overlap-only relaxation');
if (!builtMain.includes('Math.log1p(Number(file.stat?.size || 0))')) throw new Error('Vault-wide file-size node scaling is missing');
if (builtMain.includes('buildTerrain()') || builtMain.includes('terrainImage(colors)')) throw new Error('Decorative Gaussian terrain is still bundled');
if (fs.readFileSync(path.join(root, 'styles.css'), 'utf8').includes('background:radial-gradient')) throw new Error('Semantic map must not use decorative background shading');
if (!modalSource.includes('this.resultContainerEl') || !modalSource.includes("querySelector('.prompt-results')") || modalSource.includes("querySelector('.suggestion-container')")) throw new Error('Search map is not mounted to the current Obsidian SuggestModal result container');
if (!fs.readFileSync(path.join(root, 'styles.css'), 'utf8').includes('.is-map-visible .prompt-results')) throw new Error('Desktop semantic map layout is not applied to Obsidian prompt results');
if (!fs.readFileSync(path.join(root, 'styles.css'), 'utf8').includes('.gib-search-modal:not(.is-map-visible) .prompt-results{min-height:0;flex:1 1 auto;overflow-y:auto')) throw new Error('List-only search results are not independently scrollable');
if (!builtMain.includes('topographicMapIntroduced')) throw new Error('Desktop semantic map introduction migration is missing');
if (!builtMain.includes('immediate ? 0 : 75')) throw new Error('Live semantic search debounce is missing');
if (!builtMain.includes('if (this.indexRun)')) throw new Error('Serialized index scheduling is missing');
if (!builtMain.includes('clearTimeout(this.updateTimer)')) throw new Error('Vault-wide index event coalescing is missing');
if (builtMain.includes('this.pending.get(file.path)')) throw new Error('Per-file full-index timers must not be used');
if (!builtMain.includes('contextualExpression') || !builtMain.includes('indexedHighlightCandidates')) throw new Error('Indexed contextual phrase scoring is missing');
if (builtMain.includes('function phraseCandidates(')) throw new Error('Legacy isolated n-gram highlighting is still bundled');
if (/device\s*:\s*["'](?:wasm|webgpu)["']/.test(builtMain)) throw new Error('Inference device must be selected by the host runtime');
if (/process\?\.release\?\.name\s*===\s*["']node["']/.test(builtMain)) throw new Error('Release build still contains Electron Node runtime detection');
if (/\.(?:values|keys|entries)\(\)\.(?:map|filter|reduce|some|every|find|sort|slice)\b/.test(runtimeSource)) throw new Error('Runtime uses iterator helpers unavailable in the minimum release environment');

const codeFiles = [
  'main.js', 'src/main.js', 'src/mobile-runtime.js', 'src/desktop-embed-worker.js', 'styles.css',
];
const forbidden = [
  /\x62\x65\x74\x74\x65\x72\x20\x63\x6c\x61\x75\x64\x65/i,
  /\b\x63\x6c\x61\x75\x64\x65\b/i,
  /\b\x63\x6f\x64\x65\x78\b/i,
  /\b\x63\x68\x61\x74\x67\x70\x74\b/i,
  /\bbc embed\b/i, /agent's semantic_search/i, /sdk mcp/i,
  /C:\\Users\\/i, /[A-Z]:\\Tucker\\/i, /console\.(?:log|debug)\s*\(/,
];
for (const relativePath of codeFiles) {
  const source = fs.readFileSync(path.join(root, relativePath), 'utf8');
  for (const pattern of forbidden) {
    if (relativePath === 'main.js' && String(pattern).includes('console')) continue;
    if (pattern.test(source)) throw new Error(`${relativePath} contains forbidden public-release text: ${pattern}`);
  }
  if (/\.(?:js|mjs)$/.test(relativePath)) execFileSync(process.execPath, ['--check', path.join(root, relativePath)], { stdio: 'inherit' });
}

const { MobileSearchRuntime, buildHighlightCandidates, conceptLabelCandidates } = await import(pathToFileURL(path.join(root, 'src', 'mobile-runtime.js')).href);
const desktopBatchSizes = [];
const batchRuntime = new MobileSearchRuntime({ isMobile: false, manifest: { id: 'gib-search' }, app: { vault: { adapter: { getBasePath: () => 'batch-test' }, configDir: '.obsidian', getName: () => 'batch-test' } }, desktopEmbedder: { embedBatch: async texts => { desktopBatchSizes.push(texts.length); return texts.map(() => new Float32Array(384)); } } });
const batchedVectors = await batchRuntime.embedBatch(Array.from({ length: 19 }, (_, index) => `passage ${index}`), false, 8);
if (batchedVectors.length !== 19 || desktopBatchSizes.join(',') !== '8,8,3') throw new Error(`Desktop embedding batches are unbounded: ${desktopBatchSizes.join(',')}`);
let storedIndex = null; const storagePlugin = { isMobile: false, manifest: { id: 'gib-search' }, logDiagnostic() {}, desktopIndexStore: { put: async value => { storedIndex = value; }, get: async () => storedIndex }, app: { vault: { adapter: { getBasePath: () => 'storage-test' }, configDir: '.obsidian', getName: () => 'storage-test' } } };
const storageRuntime = new MobileSearchRuntime(storagePlugin); storageRuntime.meta = [{ file: 'test.md', highlightCandidates: [{ phrase: 'free will', field: 'body' }] }]; storageRuntime.vectors = [new Float32Array(384).fill(.25)]; storageRuntime.highlightVectors = [[new Int16Array(384).fill(16384)]]; await storageRuntime.saveIndex();
if (storedIndex.highlightVectors.byteLength !== 384 * 2) throw new Error('Highlight vectors were not persisted');
const loadedRuntime = new MobileSearchRuntime(storagePlugin); await loadedRuntime.loadIndex();
if (loadedRuntime.highlightVectors.length !== 1 || loadedRuntime.highlightVectors[0].length !== 1 || loadedRuntime.highlightVectors[0][0][0] !== 16384) throw new Error('Highlight vectors did not survive save/load');
const coverage = buildHighlightCandidates('Topics/Agency and Parenting.md', { heading: 'Divine Sovereignty and Mans Will', text: "A parent's role is to teach the child. Raising children requires discipline and desire. Agency is opposed to determinism." });
const coveragePhrases = new Set(coverage.map(item => item.phrase.toLowerCase()));
for (const phrase of ['teach the child', 'raising children', 'divine sovereignty', 'agency', 'determinism', 'desire']) if (!coveragePhrases.has(phrase)) throw new Error(`Indexed highlighting missed ${phrase}: ${[...coveragePhrases].join(', ')}`);
for (const phrase of coveragePhrases) if (phrase === 'idea' || phrase === 'thought') throw new Error(`Generic highlight candidate leaked into the index: ${phrase}`);
const garmentLabels = conceptLabelCandidates('During the 19th-century men wore ceremonial clothing. Temple covenants explain the sacred garment.', 'mormon garment').map(item => item.phrase.toLowerCase()); if (garmentLabels.includes('19th-century men') || !garmentLabels.includes('temple covenants')) throw new Error(`Concept labels accepted an incidental demographic phrase or missed a coherent noun phrase: ${garmentLabels.join(', ')}`);
const mockPlugin = { isMobile: false, manifest: { id: 'gib-search' }, app: { vault: { adapter: { getBasePath: () => 'test' }, configDir: '.obsidian', getName: () => 'test' } } };
const typoRuntime = new MobileSearchRuntime(mockPlugin); typoRuntime.meta = [{ file: '02 - Notes/Evolution.md', heading: 'Human evolution', text: 'Notes about evolution and natural selection.' }]; typoRuntime.refreshLexical(); if (typoRuntime.correctQuery('evoltion') !== 'evolution') throw new Error('Single-edit vault term correction failed'); if (typoRuntime.correctQuery('evolution') !== 'evolution') throw new Error('Correct vault terms must not be changed'); let embeddedTypo = ''; typoRuntime.embed = async value => { embeddedTypo = value; return new Float32Array(384); }; await typoRuntime.queryVector('evoltion'); if (embeddedTypo !== 'evolution') throw new Error(`Semantic query embedded the uncorrected typo: ${embeddedTypo}`);
const highlighter = new MobileSearchRuntime(mockPlugin); const highlightCandidates = [{ phrase: 'agency', field: 'body', sentenceId: 0, start: 0, end: 0, words: 1, hasNoun: true, hasExpression: false, adjectiveOnly: false, quality: .04 }, { phrase: 'free will', field: 'body', sentenceId: 0, start: 2, end: 3, words: 2, hasNoun: true, hasExpression: false, adjectiveOnly: false, quality: .09 }];
highlighter.highlightVectors = [[new Int16Array([Math.round(.68 * 32767)]), new Int16Array([Math.round(.84 * 32767)])]];
const highlightResults = [{ file: 'agency.md', heading: '', text: 'Agency protects free will.', passageIndex: 0, semanticScore: .8, highlightCandidates }];
await highlighter.semanticHighlights(highlightResults, new Float32Array([1]), { query: 'free will', resultMinScore: .55, singleWordMinScore: .62, phraseMinScore: .56, maxPhrases: 5 });
const directPhrases = highlightResults[0].semanticHighlights.map(item => item.phrase.toLowerCase());
if (!directPhrases.includes('agency') || !directPhrases.includes('free will')) throw new Error(`Precomputed semantic highlighting failed: ${directPhrases.join(', ')}`);
const mapRuntime = new MobileSearchRuntime(mockPlugin); mapRuntime.meta = [{ file: 'A.md' }, { file: 'B.md' }, { file: 'C.md' }]; mapRuntime.vectors = [new Float32Array(384), new Float32Array(384), new Float32Array(384)]; mapRuntime.vectors[0][0] = 1; mapRuntime.vectors[1][0] = .9; mapRuntime.vectors[1][1] = .1; mapRuntime.vectors[2][1] = 1;
const semanticMap = mapRuntime.semanticMap(['A.md', 'B.md', 'C.md']); if (semanticMap.nodes.length !== 3 || !semanticMap.edges.some(edge => new Set([edge.source, edge.target]).has('A.md') && new Set([edge.source, edge.target]).has('B.md'))) throw new Error('Semantic map does not preserve close note relationships');
const emptyStarfield = await mapRuntime.semanticStarfield('', ['A.md', 'B.md', 'C.md']); if (emptyStarfield.nodes.length !== 3 || !emptyStarfield.nodes.every(node => Number.isFinite(node.x) && Number.isFinite(node.y) && Number.isFinite(node.topicHue) && Number.isFinite(node.topicAngle) && Number.isFinite(node.uniqueness) && node.uniqueness >= 0 && node.uniqueness <= 1) || !emptyStarfield.edges.length || !emptyStarfield.edges.every(edge => edge.residualScore === 0)) throw new Error('Clustered topic-compass vault starfield or uniqueness percentile is not available before a query');
const neighborhood = mapRuntime.semanticNeighbors('A.md', 2); if (neighborhood.nodes[0]?.id !== 'B.md') throw new Error('Note neighborhood does not rank the closest note first'); if (!neighborhood.nodes.every(node => Number.isFinite(node.x) && Number.isFinite(node.y))) throw new Error('Residual semantic projection did not produce stable angular coordinates'); if (neighborhood.edges.length !== 1) throw new Error('Note neighborhood is missing semantic spring forces');
mapRuntime.queryVector = async () => mapRuntime.vectors[0]; const queryMap = await mapRuntime.semanticQueryMap('A', ['A.md', 'B.md', 'C.md']); if (queryMap.edges.length !== 3 || !queryMap.nodes.every(node => Number.isFinite(node.semanticScore)) || !queryMap.edges.every(edge => Number.isFinite(edge.score) && Number.isFinite(edge.residualScore))) throw new Error('Semantic map does not expose complete three-layer relationship data');
const queryStarfield = await mapRuntime.semanticStarfield('A', ['A.md', 'B.md', 'C.md']); if (!queryStarfield.nodes.every(node => Number.isFinite(node.semanticScore)) || !queryStarfield.edges.every(edge => Number.isFinite(edge.residualScore))) throw new Error('Semantic starfield does not adapt to the query');
const reducedNodes = queryStarfield.nodes.map((node, index) => ({ ...node, relevance: 1 - index * .35 })), reducedLayout = await mapRuntime.multiRelationalLayout('A', reducedNodes); if (reducedLayout.size !== 3 || ![...reducedLayout.values()].every(point => Number.isFinite(point.x) && Number.isFinite(point.y))) throw new Error('Query-conditioned multi-relational reduction did not produce a complete finite layout'); const argumentLayout = await mapRuntime.multiRelationalLayout('A', reducedNodes, new Map(), { lens: 'arguments' }), enrichedLayout = await mapRuntime.multiRelationalLayout('A', reducedNodes, new Map([[['B.md', 'C.md'].sort().join('\0'), { type: 'contrast', confidence: .9 }]]), { lens: 'arguments' }); if ([...argumentLayout].every(([id, point]) => Math.hypot(point.x - enrichedLayout.get(id).x, point.y - enrichedLayout.get(id).y) < 1e-5)) throw new Error('Relationship evidence did not update the argument distance layout');
const angularRuntime = new MobileSearchRuntime(mockPlugin), angularValues = [[.7, .714, 0], [.7, -.714, 0], [.7, 0, .714], [.7, 0, -.714]]; angularRuntime.meta = angularValues.map((_, index) => ({ file: `Facet-${index}.md` })); angularRuntime.vectors = angularValues.map(values => { const vector = new Float32Array(384), norm = Math.hypot(...values); values.forEach((value, index) => { vector[index] = value / norm; }); return vector; }); angularRuntime.queryVector = async () => { const vector = new Float32Array(384); vector[0] = 1; return vector; }; const angularLayout = await angularRuntime.multiRelationalLayout('shared query', angularRuntime.meta.map(item => ({ id: item.file, relevance: .5, generation: 1 }))), angularMean = [...angularLayout.values()].reduce((sum, point) => ({ x: sum.x + point.x / angularLayout.size, y: sum.y + point.y / angularLayout.size }), { x: 0, y: 0 }); if (Math.hypot(angularMean.x, angularMean.y) > .12) throw new Error(`Centered conceptual facets still lean to one side: ${JSON.stringify(angularMean)}`);
const vaultCenterRuntime = new MobileSearchRuntime(mockPlugin), vaultCenterValues = [[1, 0, 0], [.995, .1, 0], [.995, -.1, 0], [0, 0, 1]]; vaultCenterRuntime.meta = vaultCenterValues.map((_, index) => ({ file: `Vault-${index}.md` })); vaultCenterRuntime.vectors = vaultCenterValues.map(values => { const vector = new Float32Array(384), norm = Math.hypot(...values); values.forEach((value, index) => { vector[index] = value / norm; }); return vector; }); const vaultCenteredLayout = await vaultCenterRuntime.multiRelationalLayout('', vaultCenterRuntime.meta.map((item, index) => ({ id: item.file, relevance: 0, generation: 1, x: index === 3 ? .8 : .08 + index * .02, y: index === 1 ? .03 : index === 2 ? -.03 : 0 })), new Map(), { vaultCenter: true }), mainIsland = [0, 1, 2].reduce((sum, index) => ({ x: sum.x + vaultCenteredLayout.get(`Vault-${index}.md`).x / 3, y: sum.y + vaultCenteredLayout.get(`Vault-${index}.md`).y / 3 }), { x: 0, y: 0 }), outlierIsland = vaultCenteredLayout.get('Vault-3.md'); if (Math.hypot(outlierIsland.x - mainIsland.x, outlierIsland.y - mainIsland.y) < .5) throw new Error('Thresholded vault positions were not preserved by the final layout');
const labelRuntime = new MobileSearchRuntime(mockPlugin), labelFiles = ['Garment-A.md', 'Garment-B.md', 'Garment-C.md'], labelVector = new Float32Array(384); labelVector[0] = .8; labelVector[1] = .6; labelRuntime.meta = labelFiles.map(file => ({ file, highlightCandidates: [{ phrase: 'Temple covenants', field: 'body' }, ...(file === labelFiles[0] ? [{ phrase: 'common underwear', field: 'body' }] : [])] })); labelRuntime.vectors = labelFiles.map(() => Float32Array.from(labelVector)); const templeVector = Int16Array.from(labelVector, value => Math.round(value * 32767)), underwearVector = new Int16Array(384); underwearVector[0] = Math.round(.8 * 32767); underwearVector[2] = Math.round(.6 * 32767); labelRuntime.highlightVectors = labelRuntime.meta.map((_, index) => [templeVector, ...(index === 0 ? [underwearVector] : [])]); const labelQuery = new Float32Array(384); labelQuery[0] = 1; const semanticLabels = labelRuntime.conceptFacetsFromVector(labelQuery, labelFiles, 'mormon garment'); if (![...semanticLabels.values()].every(value => value.label === 'Temple Covenants' && value.confidence >= .44)) throw new Error(`Semantic cluster labeling preferred an incidental phrase: ${JSON.stringify([...semanticLabels.values()])}`);
const speakerRuntime = new MobileSearchRuntime(mockPlugin); speakerRuntime.meta = [{ file: 'One.md', text: 'Operator: A discussion of divine nature.' }, { file: 'Two.md', text: 'Operator: Notes about biblical theology.' }, { file: 'Three.md', text: 'A separate meditation.' }]; const structuralSpeakers = speakerRuntime.structuralSpeakerLabels(['One.md', 'Two.md', 'Three.md']); if (!structuralSpeakers.has('operator')) throw new Error('Repeated transcript speakers are not excluded from topical labels');
if (mainSource.includes('Mixed Topic')) throw new Error('Generic mixed-topic labels must not be rendered as meaningful communities');
const facets = await mapRuntime.conceptFacets('A', ['A.md', 'B.md', 'C.md']); if (facets.size !== 3 || ![...facets.values()].every(value => Number.isInteger(value.facet) && value.affinities && Number.isFinite(value.confidence))) throw new Error('Relevance did not produce complete soft concept facets'); const localFacets = mapRuntime.conceptFacetsFromFile('A.md', ['B.md', 'C.md']); if (localFacets.size !== 2) throw new Error('Local concept facets are not conditioned on the active note vector'); const context = mapRuntime.contextScores(['A.md', 'B.md', 'C.md']); if (context.size !== 3 || ![...context.values()].every(value => Number.isFinite(value) && value >= 0 && value <= 1)) throw new Error('Context lens did not produce bounded vault-context scores'); for (const lens of ['relevance', 'arguments', 'context']) { const lensNodes = reducedNodes.map((node, index) => ({ ...node, facet: index > 1 ? 1 : 0 })), layout = await mapRuntime.multiRelationalLayout('A', lensNodes, new Map([[['B.md', 'C.md'].sort().join('\0'), { type: 'contrast', confidence: .9 }]]), { lens }); if (layout.size !== 3 || ![...layout.values()].every(point => Number.isFinite(point.x) && Number.isFinite(point.y))) throw new Error(`${lens} lens did not produce a complete finite layout`); } const localLayout = await mapRuntime.multiRelationalLayout('A', reducedNodes.slice(1), new Map(), { lens: 'arguments', centerFile: 'A.md' }); if (localLayout.size !== 2 || ![...localLayout.values()].every(point => Number.isFinite(point.x) && Number.isFinite(point.y))) throw new Error('Active-note argument layout is incomplete');
const relationRuntime = new MobileSearchRuntime(mockPlugin); relationRuntime.meta = [{ file: 'A.md', contentHash: 'a', text: 'Free will permits meaningful choice.', entities: ['Free will'] }, { file: 'B.md', contentHash: 'b', text: 'Every choice is completely predetermined.', entities: ['Determinism'] }]; relationRuntime.classifyRelationPairs = async () => [{ contradiction: .8, neutral: .1, entailment: .1 }, { contradiction: .76, neutral: .14, entailment: .1 }]; relationRuntime.saveRelationCache = async () => {}; const relationships = await relationRuntime.graphRelationships([{ source: 'A.md', target: 'B.md', affinity: .9, sourceEvidence: 'People can genuinely choose.', targetEvidence: 'Every choice is predetermined.' }], 1), classifiedRelation = relationships.get(['A.md', 'B.md'].sort().join('\0')); if (classifiedRelation?.type !== 'contrast' || relationRuntime.relationCache.size !== 1 || classifiedRelation.evidence?.['A.md'] !== 'People can genuinely choose.' || classifiedRelation.evidence?.['B.md'] !== 'Every choice is predetermined.') throw new Error('Bounded relationship classification, evidence, or caching failed');
const argumentEdges = mapRuntime.argumentCandidateEdges(['A.md', 'B.md', 'C.md']); if (argumentEdges.length !== 3 || !new Set(argumentEdges.slice(0, 2).flatMap(edge => [edge.source, edge.target])).has('C.md') || !argumentEdges.slice(0, 2).every(edge => edge.affinity > 2)) throw new Error('Pairwise argument candidates do not prioritize a spanning comparison without an anchor');
const generations = mapRuntime.semanticGenerations(['A.md'], 3, 1); if (generations.nodes.length !== 3 || generations.nodes[1]?.id !== 'B.md' || generations.nodes[1]?.generation !== 2 || generations.nodes[2]?.generation !== 3 || generations.edges.length !== 2) throw new Error('Semantic generations do not expand one bounded layer at a time');
const clusterRuntime = new MobileSearchRuntime(mockPlugin), clusteredVectors = [[1, 0], [.995, .1], [.995, -.1], [0, 1], [.1, .995], [-.1, .995]].map(values => { const vector = new Float32Array(384), norm = Math.hypot(...values); values.forEach((value, index) => { vector[index] = value / norm; }); return vector; }); clusterRuntime.meta = clusteredVectors.map((_, index) => ({ file: `${index < 3 ? 'Alpha' : 'Beta'}-${index}.md` })); clusterRuntime.vectors = clusteredVectors; const clustered = await clusterRuntime.semanticStarfield('', clusterRuntime.meta.map(item => item.file)), communityByFile = new Map(clustered.nodes.map(node => [node.id, node.community])); if (communityByFile.get('Alpha-0.md') !== communityByFile.get('Alpha-1.md') || communityByFile.get('Beta-3.md') !== communityByFile.get('Beta-4.md') || communityByFile.get('Alpha-0.md') === communityByFile.get('Beta-3.md')) throw new Error('Louvain clustering did not separate obvious semantic communities');
const thresholdRuntime = new MobileSearchRuntime(mockPlugin); thresholdRuntime.meta = Array.from({ length: 20 }, (_, index) => ({ file: `${index < 10 ? 'North' : 'South'}-${index}.md` })); thresholdRuntime.vectors = thresholdRuntime.meta.map((_, index) => { const vector = new Float32Array(384), offset = (index % 10 - 4.5) * .012; vector[index < 10 ? 0 : 1] = Math.sqrt(1 - offset * offset); vector[2] = offset; return vector; }); const thresholdGraph = await thresholdRuntime.semanticStarfield('', thresholdRuntime.meta.map(item => item.file)), thresholdLayout = await thresholdRuntime.multiRelationalLayout('', thresholdGraph.nodes.map(node => ({ ...node, generation: 1 })), new Map(), { vaultCenter: true }), withinDistances = [], crossDistances = []; for (let first = 0; first < thresholdGraph.nodes.length; first++) for (let second = first + 1; second < thresholdGraph.nodes.length; second++) { const a = thresholdLayout.get(thresholdGraph.nodes[first].id), b = thresholdLayout.get(thresholdGraph.nodes[second].id), distance = Math.hypot(a.x - b.x, a.y - b.y); ((first < 10) === (second < 10) ? withinDistances : crossDistances).push(distance); } const averageDistance = values => values.reduce((sum, value) => sum + value, 0) / values.length, withinAverage = averageDistance(withinDistances), crossAverage = averageDistance(crossDistances); if (withinAverage >= crossAverage * .62 || Math.min(...thresholdGraph.nodes.map(node => node.uniqueness)) !== 0 || Math.max(...thresholdGraph.nodes.map(node => node.uniqueness)) !== 1) throw new Error(`Adaptive-neighbor layout or vault-wide uniqueness percentile is not separating semantic neighborhoods (${withinAverage.toFixed(3)} within vs ${crossAverage.toFixed(3)} across)`);

for (const required of ['main.js', 'manifest.json', 'styles.css', 'versions.json', 'README.md', 'LICENSE', 'SECURITY.md']) {
  if (!fs.existsSync(path.join(root, required))) throw new Error(`Missing public release file: ${required}`);
}

console.log(`Gib Search ${manifest.version} passed build, syntax, manifest, and public-content checks.`);
