import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import { execFileSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
execFileSync(process.execPath, [path.join(root, 'scripts', 'build.mjs')], { stdio: 'inherit' });
const buildSource = fs.readFileSync(path.join(root, 'scripts', 'build.mjs'), 'utf8');
if (!buildSource.includes("'process.release.name': '\"browser\"'")) throw new Error('Obsidian renderer must use the browser inference runtime');

const manifest = JSON.parse(fs.readFileSync(path.join(root, 'manifest.json'), 'utf8'));
if (manifest.id !== 'gib-search') throw new Error('manifest id must be gib-search');
if (manifest.name !== 'Gib Search') throw new Error('manifest name must be Gib Search');
if (!/^0\.\d+\.\d+$/.test(manifest.version)) throw new Error('public beta versions must remain in 0.x.x');
if (manifest.isDesktopOnly) throw new Error('Gib Search must remain available on mobile');

const builtMain = fs.readFileSync(path.join(root, 'main.js'), 'utf8');
const runtimeSource = fs.readFileSync(path.join(root, 'src', 'mobile-runtime.js'), 'utf8'); const semanticSource = runtimeSource.slice(runtimeSource.indexOf('async semanticHighlights('), runtimeSource.indexOf('cacheResult(', runtimeSource.indexOf('async semanticHighlights(')));
const mainSource = fs.readFileSync(path.join(root, 'src', 'main.js'), 'utf8'), workerSource = fs.readFileSync(path.join(root, 'src', 'desktop-embed-worker.js'), 'utf8'); const modalSource = mainSource.slice(mainSource.indexOf('class SemanticSearchModal'), mainSource.indexOf('class SemanticInNoteSearch')), physicsSource = mainSource.slice(mainSource.indexOf('physicsStep(alpha)'), mainSource.indexOf('startSimulation(', mainSource.indexOf('physicsStep(alpha)')));
const embeddedWasm = builtMain.match(/EMBEDDED_WASM_GZIP\s*=\s*["']([^"']+)["']/);
if (!embeddedWasm) throw new Error('main.js does not contain the bundled WebAssembly runtime');
const embeddedWasmModule = builtMain.match(/EMBEDDED_WASM_MODULE_GZIP\s*=\s*["']([^"']+)["']/);
if (!embeddedWasmModule) throw new Error('main.js does not contain the bundled WebAssembly loader');
const bundledBinary = zlib.gunzipSync(Buffer.from(embeddedWasm[1], 'base64'));
const bundledModule = zlib.gunzipSync(Buffer.from(embeddedWasmModule[1], 'base64')).toString('utf8');
const sourceBinary = fs.readFileSync(path.join(root, 'node_modules', '@huggingface', 'transformers', 'dist', 'ort-wasm-simd-threaded.jsep.wasm'));
if (!bundledBinary.equals(sourceBinary)) throw new Error('Bundled WebAssembly runtime differs from the pinned dependency');
if (!bundledModule.includes('n=false') || !bundledModule.includes('var isNode = false;')) throw new Error('Bundled WebAssembly loader can still select Node worker modules');
if (!bundledModule.includes('Xa??="embedded.wasm"')) throw new Error('Bundled WebAssembly loader still depends on its module URL');
if (!builtMain.includes('wasmBinary = this.plugin.embeddedWasmBinary')) throw new Error('Bundled WebAssembly runtime is not connected to inference');
if (!builtMain.includes('wasmPaths = { mjs: this.plugin.embeddedWasmModuleUrl }')) throw new Error('Bundled WebAssembly loader is not connected to inference');
if (!builtMain.includes('new window.Worker')) throw new Error('Desktop inference is not isolated in a browser worker');
if (!builtMain.includes('web-worker-wasm')) throw new Error('Desktop worker health reporting is missing');
if (builtMain.includes("require('node:worker_threads')") || builtMain.includes("require('node:child_process')") || builtMain.includes('ELECTRON_RUN_AS_NODE')) throw new Error('Unsupported Node background runtime is still bundled');
if (!builtMain.includes('embedQueue = embedQueue.then')) throw new Error('Desktop inference requests are not serialized');
if (!builtMain.includes('index.highlights.bin') || !builtMain.includes('highlightCandidates') || !builtMain.includes('packedHighlightVectors')) throw new Error('Precomputed semantic highlight index is missing');
if (builtMain.includes('cachedPassageVectors')) throw new Error('Search-time phrase embedding is still bundled');
if (/embedBatch|initializeModel|cachedPassageVectors/.test(semanticSource)) throw new Error('Semantic highlighting still performs search-time inference');
if (!builtMain.includes('contentFingerprint(content)') || !builtMain.includes('sameChunks(previous')) throw new Error('Index change detection still depends only on file timestamps');
if (!builtMain.includes('this.plugin.app.vault.read(file)')) throw new Error('Index verification still uses potentially stale cached vault reads');
if (!builtMain.includes('Index pair is incomplete') || !builtMain.includes('attempt < 40')) throw new Error('Desktop index loading does not retry transient sync races');
if (builtMain.includes('if (!existingDirectory) return undefined')) throw new Error('Desktop index loading skips retries when sync temporarily removes the index directory');
if (!builtMain.includes("if (!this.isMobile) throw error")) throw new Error('Desktop index load failures can still trigger an empty rebuild');
if (!builtMain.includes('retainedMeta.push') || builtMain.includes('const remove = new Set([...changed.map')) throw new Error('Index refresh can still discard changed files before their replacements are ready');
if (!builtMain.includes('waitForVaultSettled') || !builtMain.includes('Waiting for the vault to finish loading')) throw new Error('Startup can still scan a partial Obsidian vault');
if (builtMain.includes('this.highlightTimer') || builtMain.includes('quickLimit = Math.min(4')) throw new Error('Search results still render before semantic highlighting finishes');
if (!builtMain.includes('semanticHighlights: tweaks.semanticHighlights')) throw new Error('Semantic highlighting is not part of the initial result render');
if (builtMain.includes("if (!this.vectors.length) throw new Error(this.message || 'The semantic index is not ready'); await this.initializeModel()")) throw new Error('Desktop search still warms BGE on the UI thread');
if (!builtMain.includes('searchLive(query')) throw new Error('Live semantic query scheduling is missing');
if (!runtimeSource.includes('correctQuery(query)') || !runtimeSource.includes('editDistanceWithin(lower, candidate, 1)') || !runtimeSource.includes('queryVector(correctedQuery)')) throw new Error('Vault-derived typo-tolerant semantic queries are missing');
if (!builtMain.includes('SemanticMapCanvas') || !builtMain.includes('Open note neighborhood') || !builtMain.includes('Explore from note')) throw new Error('Semantic search map or note neighborhood UI is missing');
if (!builtMain.includes('semanticQueryMap(query, files)') || !builtMain.includes('semanticStarfield(query, files = null, focusFiles = [])') || !builtMain.includes('semanticNeighbors(file')) throw new Error('Local semantic map data is missing');
if (!builtMain.includes('LivingSemanticMapCanvas') || !builtMain.includes('graph.edges || []')) throw new Error('Living semantic force map or note gravity is missing');
if (!modalSource.includes('new LivingSemanticMapCanvas') || modalSource.includes('this.map = new SemanticMapCanvas')) throw new Error('Search modal is not using the living semantic force map');
if (!mainSource.includes('distance < closestDistance') || !modalSource.includes('wasSelected !== isSelected') || !modalSource.includes('attributeOldValue: true')) throw new Error('Graph hover can select an overlapping or stale result instead of the pointed node');
if (!mainSource.includes('this.startSimulation(previous.size ? .82 : 1)') || !mainSource.includes("id: '__query__'") || !mainSource.includes('(query.layoutX - query.x) * .012')) throw new Error('Persistent animated query target is missing');
if (/buildSemanticHeatField|triangulateTerrain|quadraticCurveTo/.test(mainSource)) throw new Error('Obsolete decorative terrain rendering remains in the semantic map');
if (!mainSource.includes('semanticDensityField(width, height)') || !mainSource.includes('generationWeight') || !mainSource.includes('!edge.crossCommunity && edge.strength > .14') || !mainSource.includes('const levels = [.35, .62, .95, 1.35, 1.9, 2.6]') || !mainSource.includes('traceDensityLevel(ctx, field, level)')) throw new Error('Semantic-support density, bounded relationship ridges, or fixed contour elevations are missing');
if (!mainSource.includes('node.matched && node.generation === 1') || !mainSource.includes('addRidge(center, target') || !mainSource.includes('(supportMaximum * 1.18 + .42) * this.queryPresence')) throw new Error('Query or local-note terrain summit and direct-result ridges are missing');
if (!mainSource.includes('suppressEmptySummits(values, columns, rows, step, anchors, sigma)') || !mainSource.includes('height - (anchorHeight - .025)') || !mainSource.includes('values[row * columns + column] += amplitude * Math.exp') || !mainSource.includes('values[index] - depression[index]')) throw new Error('Additive terrain or localized empty-summit correction is missing');
if (!mainSource.includes("this.center?.id ? 'Local note' : 'Search origin'") || !mainSource.includes('ctx.lineTo(queryX + marker * .72, queryY)') || !mainSource.includes('this.queryMarkerFocus * 1.2') || !mainSource.includes('Number(b.query) - Number(a.query)') || !mainSource.includes('chosen.leader')) throw new Error('Cartographic summit marker, map labels, or collision-aware leader lines are missing');
if (!mainSource.includes('now - Number(this.lastTerrainAt || 0) >= 48') || !mainSource.includes('this.terrainMask')) throw new Error('Semantic terrain is not cached during animation');
if (mainSource.includes('node.matched && (node.accent > .01 || active)') || !mainSource.includes('if (focused && !queryFocused) labelNodes.add(focused)')) throw new Error('Result rings or always-visible map labels remain');
if (!mainSource.includes('this.byId.get(this.hovered) || this.byId.get(this.selected)') || !mainSource.includes('this.hovered = id; this.updateDetail();')) throw new Error('Map detail is not limited to hovered or selected results');
if (!mainSource.includes('collisionDistance = .035') || !mainSource.includes('(node.layoutX - node.x) * .018')) throw new Error('Calculated-layout relaxation or size-aware collision is missing');
if (!mainSource.includes('relationship = focused && !queryFocused') || !mainSource.includes('.18 + related * .76')) throw new Error('Line-free semantic hover emphasis is missing');
if (!runtimeSource.includes('louvainCommunities(ids, edges)') || !runtimeSource.includes('const reverse = directed[second].get(first)') || !runtimeSource.includes('consolidateCommunities(entries') || !runtimeSource.includes('weights.community * community ** 2')) throw new Error('Mutual-neighbor communities are not represented in the combined distance model');
if (!mainSource.includes('distance <= .92') || !mainSource.includes('(distance - .92) * .045') || physicsSource.includes('for (const edge of this.activeEdges') || physicsSource.includes('edge.residual')) throw new Error('Physics is not limited to target relaxation, collision cleanup, and emergency corralling');
if (!modalSource.includes('results = this.lastResults.slice(0, 80)') || !modalSource.includes('semanticStarfield(query, query ? activeFiles : paths, activeFiles)') || !modalSource.includes('.08 + rankedRelevance * .92')) throw new Error('Query map is not scoped to visible results or using the full relevance range');
if (!runtimeSource.includes('semanticTopicBasis(entries)') || !runtimeSource.includes('topicCoordinates(entries, queryVector, basis.axes)') || !runtimeSource.includes('angular ** 2') || !mainSource.includes('node.topicHue')) throw new Error('Stable topic compass coordinates, distance contribution, or semantic hues are missing');
if (!runtimeSource.includes('extractGraphEntities(source)') || !runtimeSource.includes('entityAffinity =') || !runtimeSource.includes('entityBoost')) throw new Error('Entity-aware indexing, graph neighborhoods, or reranking is missing');
if (!runtimeSource.includes("RELATION_MODEL_ID = 'Xenova/mobilebert-uncased-mnli'") || !runtimeSource.includes('graphRelationships(edges, budget') || !modalSource.includes('argumentCandidateEdges(candidates.map') || !mainSource.includes('graphRelationshipBudgetMobile')) throw new Error('Budgeted local relationship intelligence is missing');
if (!builtMain.includes('index.relationships.json') || !runtimeSource.includes('saveRelationCache()') || !runtimeSource.includes('missing.length < maximum')) throw new Error('Relationship inference is not persistently cached or bounded');
if (workerSource.includes("message.type === 'relations') embedQueue") || !modalSource.includes('window.setTimeout(resolve, 180)') || !modalSource.includes('version !== this.lensVersion')) throw new Error('Relationship intelligence can block or outrun live search input');
if (!mainSource.includes('this.hasQuery && !this.pendingQuery ? foreground : this.nodes') || !mainSource.includes('this.pendingQuery') || !mainSource.includes('this.cameraZoom')) throw new Error('Calculated foreground isolation, pending-query transition, or zoom is missing');
if (mainSource.includes('ctx.filter') || mainSource.includes('parallaxX')) throw new Error('Distracting background blur or parallax remains in the search map');
if (!runtimeSource.includes('semanticGenerations(seedFiles') || !modalSource.includes('searchMapGenerations') || !mainSource.includes('gib-search-map-generations')) throw new Error('On-map semantic generation controls are missing');
if (!mainSource.includes("addEventListener('wheel'") || !mainSource.includes('this.panning =') || !mainSource.includes('this.pinch =') || !mainSource.includes('setUserZoom(value') || !mainSource.includes('resetViewport()') || !mainSource.includes('this.panX')) throw new Error('Graph pan, cursor-centered zoom, pinch zoom, or fit controls are missing');
if (!runtimeSource.includes('residualVector(entry.vector, queryVector)')) throw new Error('Search-map grouping still includes the shared query direction');
if (!runtimeSource.includes('multiRelationalLayout(query, nodes') || !runtimeSource.includes('classicalDistanceLayout(ids, distances, conditioned ? conceptTopics : topics)') || !runtimeSource.includes('weights.semantic * semantic ** 2') || !runtimeSource.includes('relationDistance ** 2')) throw new Error('Query-conditioned multi-relational dimensional reduction is incomplete');
if (!mainSource.includes("defaultSearchLens: 'relevance'") || !mainSource.includes('SEARCH_LENSES') || !modalSource.includes('applyLens()') || !modalSource.includes('gib-search-lens-select')) throw new Error('Coordinated search lenses or the Relevance default are missing');
if (!runtimeSource.includes('async conceptFacets(query, files)') || !runtimeSource.includes('contextScores(files)') || !runtimeSource.includes('argumentCandidateEdges(files)') || !modalSource.includes("lens === 'arguments'")) throw new Error('Concept, context, or argument lens analysis is missing');
if (!modalSource.includes("lens === 'relevance'") || !modalSource.includes('conceptAffinities') || modalSource.includes("lens === 'concepts'")) throw new Error('Concept structure is not integrated into relevance or the obsolete Concepts lens remains');
if (!runtimeSource.includes("conditioned ? ['__center__'") || !runtimeSource.includes('generation || 1) > 1') || !runtimeSource.includes('parent = positioned.get(node?.parent)')) throw new Error('Centerless vault layout or parent-relative semantic generations are missing');
if (!runtimeSource.includes('centeredVectorCloud(rawConceptEntries, primaryRawConcepts)') || !runtimeSource.includes("angle = lens === 'relevance' ? conceptAngle")) throw new Error('Relevance angles are not derived from the centered first-generation concept cloud');
if (!runtimeSource.includes('indexedConceptCandidates(queryVector') || !runtimeSource.includes('centrality * .42 + memberCoverage * .25 + distinction * .2') || !runtimeSource.includes("label: confidence >= .44")) throw new Error('Cluster labels are not grounded, centroid-ranked, and confidence-gated');
if (modalSource.includes("lensLabel = result === anchor ? 'Anchor'") || modalSource.includes('source.slice(1,') || !modalSource.includes("result.lensLabel = 'Position'") || !modalSource.includes('Comparing positions')) throw new Error('Argument analysis is still anchored to the first search result');
if (!runtimeSource.includes('evidence-v1') || !runtimeSource.includes('evidence: item.evidence') || !modalSource.includes('argumentEvidenceText(candidateByFile.get') || !modalSource.includes('gib-semantic-argument-compared')) throw new Error('Argument cards do not preserve and render auditable passage evidence');
if (!mainSource.includes("class NeighborhoodView") || !mainSource.includes("'aria-label': 'Local note lens'") || !mainSource.includes('centerFile: file.path') || !mainSource.includes('conceptFacetsFromFile(file.path')) throw new Error('Local-note lenses are not conditioned on the active note');
if (mainSource.includes('residual: support ?') || physicsSource.includes('relation')) throw new Error('Relationship judgments are still applied as independent graph forces');
if (!builtMain.includes('Math.log1p(Number(file.stat?.size || 0))')) throw new Error('Vault-wide file-size node scaling is missing');
if (builtMain.includes('buildTerrain()') || builtMain.includes('terrainImage(colors)')) throw new Error('Decorative Gaussian terrain is still bundled');
if (fs.readFileSync(path.join(root, 'styles.css'), 'utf8').includes('background:radial-gradient')) throw new Error('Semantic map must not use decorative background shading');
if (!modalSource.includes('this.resultContainerEl') || !modalSource.includes("querySelector('.prompt-results')") || modalSource.includes("querySelector('.suggestion-container')")) throw new Error('Search map is not mounted to the current Obsidian SuggestModal result container');
if (!fs.readFileSync(path.join(root, 'styles.css'), 'utf8').includes('.is-map-visible .prompt-results')) throw new Error('Desktop semantic map layout is not applied to Obsidian prompt results');
if (!builtMain.includes('topographicMapIntroduced')) throw new Error('Desktop semantic map introduction migration is missing');
if (!builtMain.includes('immediate ? 0 : 75')) throw new Error('Live semantic search debounce is missing');
if (!builtMain.includes('if (this.indexRun)')) throw new Error('Serialized index scheduling is missing');
if (!builtMain.includes('clearTimeout(this.updateTimer)')) throw new Error('Vault-wide index event coalescing is missing');
if (builtMain.includes('this.pending.get(file.path)')) throw new Error('Per-file full-index timers must not be used');
if (!builtMain.includes('contextualExpression') || !builtMain.includes('indexedHighlightCandidates')) throw new Error('Indexed contextual phrase scoring is missing');
if (builtMain.includes('function phraseCandidates(')) throw new Error('Legacy isolated n-gram highlighting is still bundled');
if (/device\s*:\s*["'](?:wasm|webgpu)["']/.test(builtMain)) throw new Error('Inference device must be selected by the host runtime');
if (/process\?\.release\?\.name\s*===\s*["']node["']/.test(builtMain)) throw new Error('Release build still contains Electron Node runtime detection');
if (/\.(?:values|keys|entries)\(\)\.(?:map|filter|reduce|some|every|find|sort|slice)\b/.test(runtimeSource)) throw new Error('Runtime uses iterator helpers unavailable in the minimum release environment');

const codeFiles = [
  'main.js', 'src/main.js', 'src/mobile-runtime.js', 'src/desktop-embed-worker.js', 'styles.css',
];
const forbidden = [
  /\x62\x65\x74\x74\x65\x72\x20\x63\x6c\x61\x75\x64\x65/i,
  /\b\x63\x6c\x61\x75\x64\x65\b/i,
  /\b\x63\x6f\x64\x65\x78\b/i,
  /\b\x63\x68\x61\x74\x67\x70\x74\b/i,
  /\bbc embed\b/i, /agent's semantic_search/i, /sdk mcp/i,
  /C:\\Users\\/i, /[A-Z]:\\Tucker\\/i, /console\.(?:log|debug)\s*\(/,
];
for (const relativePath of codeFiles) {
  const source = fs.readFileSync(path.join(root, relativePath), 'utf8');
  for (const pattern of forbidden) {
    if (relativePath === 'main.js' && String(pattern).includes('console')) continue;
    if (pattern.test(source)) throw new Error(`${relativePath} contains forbidden public-release text: ${pattern}`);
  }
  if (/\.(?:js|mjs)$/.test(relativePath)) execFileSync(process.execPath, ['--check', path.join(root, relativePath)], { stdio: 'inherit' });
}

const { MobileSearchRuntime, buildHighlightCandidates, conceptLabelCandidates } = await import(pathToFileURL(path.join(root, 'src', 'mobile-runtime.js')).href);
const desktopBatchSizes = [];
const batchRuntime = new MobileSearchRuntime({ isMobile: false, manifest: { id: 'gib-search' }, app: { vault: { adapter: { getBasePath: () => 'batch-test' }, configDir: '.obsidian', getName: () => 'batch-test' } }, desktopEmbedder: { embedBatch: async texts => { desktopBatchSizes.push(texts.length); return texts.map(() => new Float32Array(384)); } } });
const batchedVectors = await batchRuntime.embedBatch(Array.from({ length: 19 }, (_, index) => `passage ${index}`), false, 8);
if (batchedVectors.length !== 19 || desktopBatchSizes.join(',') !== '8,8,3') throw new Error(`Desktop embedding batches are unbounded: ${desktopBatchSizes.join(',')}`);
let storedIndex = null; const storagePlugin = { isMobile: false, manifest: { id: 'gib-search' }, logDiagnostic() {}, desktopIndexStore: { put: async value => { storedIndex = value; }, get: async () => storedIndex }, app: { vault: { adapter: { getBasePath: () => 'storage-test' }, configDir: '.obsidian', getName: () => 'storage-test' } } };
const storageRuntime = new MobileSearchRuntime(storagePlugin); storageRuntime.meta = [{ file: 'test.md', highlightCandidates: [{ phrase: 'free will', field: 'body' }] }]; storageRuntime.vectors = [new Float32Array(384).fill(.25)]; storageRuntime.highlightVectors = [[new Int16Array(384).fill(16384)]]; await storageRuntime.saveIndex();
if (storedIndex.highlightVectors.byteLength !== 384 * 2) throw new Error('Highlight vectors were not persisted');
const loadedRuntime = new MobileSearchRuntime(storagePlugin); await loadedRuntime.loadIndex();
if (loadedRuntime.highlightVectors.length !== 1 || loadedRuntime.highlightVectors[0].length !== 1 || loadedRuntime.highlightVectors[0][0][0] !== 16384) throw new Error('Highlight vectors did not survive save/load');
const coverage = buildHighlightCandidates('Topics/Agency and Parenting.md', { heading: 'Divine Sovereignty and Mans Will', text: "A parent's role is to teach the child. Raising children requires discipline and desire. Agency is opposed to determinism." });
const coveragePhrases = new Set(coverage.map(item => item.phrase.toLowerCase()));
for (const phrase of ['teach the child', 'raising children', 'divine sovereignty', 'agency', 'determinism', 'desire']) if (!coveragePhrases.has(phrase)) throw new Error(`Indexed highlighting missed ${phrase}: ${[...coveragePhrases].join(', ')}`);
for (const phrase of coveragePhrases) if (phrase === 'idea' || phrase === 'thought') throw new Error(`Generic highlight candidate leaked into the index: ${phrase}`);
const garmentLabels = conceptLabelCandidates('During the 19th-century men wore ceremonial clothing. Temple covenants explain the sacred garment.', 'mormon garment').map(item => item.phrase.toLowerCase()); if (garmentLabels.includes('19th-century men') || !garmentLabels.includes('temple covenants')) throw new Error(`Concept labels accepted an incidental demographic phrase or missed a coherent noun phrase: ${garmentLabels.join(', ')}`);
const mockPlugin = { isMobile: false, manifest: { id: 'gib-search' }, app: { vault: { adapter: { getBasePath: () => 'test' }, configDir: '.obsidian', getName: () => 'test' } } };
const typoRuntime = new MobileSearchRuntime(mockPlugin); typoRuntime.meta = [{ file: '02 - Notes/Evolution.md', heading: 'Human evolution', text: 'Notes about evolution and natural selection.' }]; typoRuntime.refreshLexical(); if (typoRuntime.correctQuery('evoltion') !== 'evolution') throw new Error('Single-edit vault term correction failed'); if (typoRuntime.correctQuery('evolution') !== 'evolution') throw new Error('Correct vault terms must not be changed'); let embeddedTypo = ''; typoRuntime.embed = async value => { embeddedTypo = value; return new Float32Array(384); }; await typoRuntime.queryVector('evoltion'); if (embeddedTypo !== 'evolution') throw new Error(`Semantic query embedded the uncorrected typo: ${embeddedTypo}`);
const highlighter = new MobileSearchRuntime(mockPlugin); const highlightCandidates = [{ phrase: 'agency', field: 'body', sentenceId: 0, start: 0, end: 0, words: 1, hasNoun: true, hasExpression: false, adjectiveOnly: false, quality: .04 }, { phrase: 'free will', field: 'body', sentenceId: 0, start: 2, end: 3, words: 2, hasNoun: true, hasExpression: false, adjectiveOnly: false, quality: .09 }];
highlighter.highlightVectors = [[new Int16Array([Math.round(.68 * 32767)]), new Int16Array([Math.round(.84 * 32767)])]];
const highlightResults = [{ file: 'agency.md', heading: '', text: 'Agency protects free will.', passageIndex: 0, semanticScore: .8, highlightCandidates }];
await highlighter.semanticHighlights(highlightResults, new Float32Array([1]), { query: 'free will', resultMinScore: .55, singleWordMinScore: .62, phraseMinScore: .56, maxPhrases: 5 });
const directPhrases = highlightResults[0].semanticHighlights.map(item => item.phrase.toLowerCase());
if (!directPhrases.includes('agency') || !directPhrases.includes('free will')) throw new Error(`Precomputed semantic highlighting failed: ${directPhrases.join(', ')}`);
const mapRuntime = new MobileSearchRuntime(mockPlugin); mapRuntime.meta = [{ file: 'A.md' }, { file: 'B.md' }, { file: 'C.md' }]; mapRuntime.vectors = [new Float32Array(384), new Float32Array(384), new Float32Array(384)]; mapRuntime.vectors[0][0] = 1; mapRuntime.vectors[1][0] = .9; mapRuntime.vectors[1][1] = .1; mapRuntime.vectors[2][1] = 1;
const semanticMap = mapRuntime.semanticMap(['A.md', 'B.md', 'C.md']); if (semanticMap.nodes.length !== 3 || !semanticMap.edges.some(edge => new Set([edge.source, edge.target]).has('A.md') && new Set([edge.source, edge.target]).has('B.md'))) throw new Error('Semantic map does not preserve close note relationships');
const emptyStarfield = await mapRuntime.semanticStarfield('', ['A.md', 'B.md', 'C.md']); if (emptyStarfield.nodes.length !== 3 || !emptyStarfield.nodes.every(node => Number.isFinite(node.x) && Number.isFinite(node.y) && Number.isFinite(node.topicHue) && Number.isFinite(node.topicAngle)) || !emptyStarfield.edges.length || !emptyStarfield.edges.every(edge => edge.residualScore === 0)) throw new Error('Clustered topic-compass vault starfield is not available before a query');
const neighborhood = mapRuntime.semanticNeighbors('A.md', 2); if (neighborhood.nodes[0]?.id !== 'B.md') throw new Error('Note neighborhood does not rank the closest note first'); if (!neighborhood.nodes.every(node => Number.isFinite(node.x) && Number.isFinite(node.y))) throw new Error('Residual semantic projection did not produce stable angular coordinates'); if (neighborhood.edges.length !== 1) throw new Error('Note neighborhood is missing semantic spring forces');
mapRuntime.queryVector = async () => mapRuntime.vectors[0]; const queryMap = await mapRuntime.semanticQueryMap('A', ['A.md', 'B.md', 'C.md']); if (queryMap.edges.length !== 3 || !queryMap.nodes.every(node => Number.isFinite(node.semanticScore)) || !queryMap.edges.every(edge => Number.isFinite(edge.score) && Number.isFinite(edge.residualScore))) throw new Error('Semantic map does not expose complete three-layer relationship data');
const queryStarfield = await mapRuntime.semanticStarfield('A', ['A.md', 'B.md', 'C.md']); if (!queryStarfield.nodes.every(node => Number.isFinite(node.semanticScore)) || !queryStarfield.edges.every(edge => Number.isFinite(edge.residualScore))) throw new Error('Semantic starfield does not adapt to the query');
const reducedNodes = queryStarfield.nodes.map((node, index) => ({ ...node, relevance: 1 - index * .35 })), reducedLayout = await mapRuntime.multiRelationalLayout('A', reducedNodes); if (reducedLayout.size !== 3 || ![...reducedLayout.values()].every(point => Number.isFinite(point.x) && Number.isFinite(point.y))) throw new Error('Query-conditioned multi-relational reduction did not produce a complete finite layout'); const argumentLayout = await mapRuntime.multiRelationalLayout('A', reducedNodes, new Map(), { lens: 'arguments' }), enrichedLayout = await mapRuntime.multiRelationalLayout('A', reducedNodes, new Map([[['B.md', 'C.md'].sort().join('\0'), { type: 'contrast', confidence: .9 }]]), { lens: 'arguments' }); if ([...argumentLayout].every(([id, point]) => Math.hypot(point.x - enrichedLayout.get(id).x, point.y - enrichedLayout.get(id).y) < 1e-5)) throw new Error('Relationship evidence did not update the argument distance layout');
const angularRuntime = new MobileSearchRuntime(mockPlugin), angularValues = [[.7, .714, 0], [.7, -.714, 0], [.7, 0, .714], [.7, 0, -.714]]; angularRuntime.meta = angularValues.map((_, index) => ({ file: `Facet-${index}.md` })); angularRuntime.vectors = angularValues.map(values => { const vector = new Float32Array(384), norm = Math.hypot(...values); values.forEach((value, index) => { vector[index] = value / norm; }); return vector; }); angularRuntime.queryVector = async () => { const vector = new Float32Array(384); vector[0] = 1; return vector; }; const angularLayout = await angularRuntime.multiRelationalLayout('shared query', angularRuntime.meta.map(item => ({ id: item.file, relevance: .5, generation: 1 }))), angularMean = [...angularLayout.values()].reduce((sum, point) => ({ x: sum.x + point.x / angularLayout.size, y: sum.y + point.y / angularLayout.size }), { x: 0, y: 0 }); if (Math.hypot(angularMean.x, angularMean.y) > .12) throw new Error(`Centered conceptual facets still lean to one side: ${JSON.stringify(angularMean)}`);
const labelRuntime = new MobileSearchRuntime(mockPlugin), labelFiles = ['Garment-A.md', 'Garment-B.md', 'Garment-C.md'], labelVector = new Float32Array(384); labelVector[0] = .8; labelVector[1] = .6; labelRuntime.meta = labelFiles.map(file => ({ file, highlightCandidates: [{ phrase: 'Temple covenants', field: 'body' }, ...(file === labelFiles[0] ? [{ phrase: 'common underwear', field: 'body' }] : [])] })); labelRuntime.vectors = labelFiles.map(() => Float32Array.from(labelVector)); const templeVector = Int16Array.from(labelVector, value => Math.round(value * 32767)), underwearVector = new Int16Array(384); underwearVector[0] = Math.round(.8 * 32767); underwearVector[2] = Math.round(.6 * 32767); labelRuntime.highlightVectors = labelRuntime.meta.map((_, index) => [templeVector, ...(index === 0 ? [underwearVector] : [])]); const labelQuery = new Float32Array(384); labelQuery[0] = 1; const semanticLabels = labelRuntime.conceptFacetsFromVector(labelQuery, labelFiles, 'mormon garment'); if (![...semanticLabels.values()].every(value => value.label === 'Temple Covenants' && value.confidence >= .44)) throw new Error(`Semantic cluster labeling preferred an incidental phrase: ${JSON.stringify([...semanticLabels.values()])}`);
const facets = await mapRuntime.conceptFacets('A', ['A.md', 'B.md', 'C.md']); if (facets.size !== 3 || ![...facets.values()].every(value => Number.isInteger(value.facet) && value.affinities && Number.isFinite(value.confidence))) throw new Error('Relevance did not produce complete soft concept facets'); const localFacets = mapRuntime.conceptFacetsFromFile('A.md', ['B.md', 'C.md']); if (localFacets.size !== 2) throw new Error('Local concept facets are not conditioned on the active note vector'); const context = mapRuntime.contextScores(['A.md', 'B.md', 'C.md']); if (context.size !== 3 || ![...context.values()].every(value => Number.isFinite(value) && value >= 0 && value <= 1)) throw new Error('Context lens did not produce bounded vault-context scores'); for (const lens of ['relevance', 'arguments', 'context']) { const lensNodes = reducedNodes.map((node, index) => ({ ...node, facet: index > 1 ? 1 : 0 })), layout = await mapRuntime.multiRelationalLayout('A', lensNodes, new Map([[['B.md', 'C.md'].sort().join('\0'), { type: 'contrast', confidence: .9 }]]), { lens }); if (layout.size !== 3 || ![...layout.values()].every(point => Number.isFinite(point.x) && Number.isFinite(point.y))) throw new Error(`${lens} lens did not produce a complete finite layout`); } const localLayout = await mapRuntime.multiRelationalLayout('A', reducedNodes.slice(1), new Map(), { lens: 'arguments', centerFile: 'A.md' }); if (localLayout.size !== 2 || ![...localLayout.values()].every(point => Number.isFinite(point.x) && Number.isFinite(point.y))) throw new Error('Active-note argument layout is incomplete');
const relationRuntime = new MobileSearchRuntime(mockPlugin); relationRuntime.meta = [{ file: 'A.md', contentHash: 'a', text: 'Free will permits meaningful choice.', entities: ['Free will'] }, { file: 'B.md', contentHash: 'b', text: 'Every choice is completely predetermined.', entities: ['Determinism'] }]; relationRuntime.classifyRelationPairs = async () => [{ contradiction: .8, neutral: .1, entailment: .1 }, { contradiction: .76, neutral: .14, entailment: .1 }]; relationRuntime.saveRelationCache = async () => {}; const relationships = await relationRuntime.graphRelationships([{ source: 'A.md', target: 'B.md', affinity: .9, sourceEvidence: 'People can genuinely choose.', targetEvidence: 'Every choice is predetermined.' }], 1), classifiedRelation = relationships.get(['A.md', 'B.md'].sort().join('\0')); if (classifiedRelation?.type !== 'contrast' || relationRuntime.relationCache.size !== 1 || classifiedRelation.evidence?.['A.md'] !== 'People can genuinely choose.' || classifiedRelation.evidence?.['B.md'] !== 'Every choice is predetermined.') throw new Error('Bounded relationship classification, evidence, or caching failed');
const argumentEdges = mapRuntime.argumentCandidateEdges(['A.md', 'B.md', 'C.md']); if (argumentEdges.length !== 3 || !new Set(argumentEdges.slice(0, 2).flatMap(edge => [edge.source, edge.target])).has('C.md') || !argumentEdges.slice(0, 2).every(edge => edge.affinity > 2)) throw new Error('Pairwise argument candidates do not prioritize a spanning comparison without an anchor');
const generations = mapRuntime.semanticGenerations(['A.md'], 3, 1); if (generations.nodes.length !== 3 || generations.nodes[1]?.id !== 'B.md' || generations.nodes[1]?.generation !== 2 || generations.nodes[2]?.generation !== 3 || generations.edges.length !== 2) throw new Error('Semantic generations do not expand one bounded layer at a time');
const clusterRuntime = new MobileSearchRuntime(mockPlugin), clusteredVectors = [[1, 0], [.995, .1], [.995, -.1], [0, 1], [.1, .995], [-.1, .995]].map(values => { const vector = new Float32Array(384), norm = Math.hypot(...values); values.forEach((value, index) => { vector[index] = value / norm; }); return vector; }); clusterRuntime.meta = clusteredVectors.map((_, index) => ({ file: `${index < 3 ? 'Alpha' : 'Beta'}-${index}.md` })); clusterRuntime.vectors = clusteredVectors; const clustered = await clusterRuntime.semanticStarfield('', clusterRuntime.meta.map(item => item.file)), communityByFile = new Map(clustered.nodes.map(node => [node.id, node.community])); if (communityByFile.get('Alpha-0.md') !== communityByFile.get('Alpha-1.md') || communityByFile.get('Beta-3.md') !== communityByFile.get('Beta-4.md') || communityByFile.get('Alpha-0.md') === communityByFile.get('Beta-3.md')) throw new Error('Louvain clustering did not separate obvious semantic communities');

for (const required of ['main.js', 'manifest.json', 'styles.css', 'versions.json', 'README.md', 'LICENSE', 'SECURITY.md']) {
  if (!fs.existsSync(path.join(root, required))) throw new Error(`Missing public release file: ${required}`);
}

console.log(`Gib Search ${manifest.version} passed build, syntax, manifest, and public-content checks.`);
