import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { IncrementalBm25, assembleIndexSegments, boundedTopK, centroidSimilarity, diverseCentroids } from '../src/search-core.js';
import { MobileSearchRuntime, chunkMarkdown, indexingHardwareProfile, queryTermWindowCandidates, semanticClauseCandidates } from '../src/mobile-runtime.js';
import { readMobileBootstrap, writeMobileBootstrap } from '../src/mobile-bootstrap.js';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const vector = (...values) => { const result = new Float32Array(384); values.forEach((value, index) => { result[index] = value; }); const norm = Math.hypot(...values) || 1; values.forEach((value, index) => { result[index] = value / norm; }); return result; };

const adapterFiles = new Map(), adapterDirectories = new Set(), memoryAdapter = { exists: async target => adapterFiles.has(target) || adapterDirectories.has(target), mkdir: async target => { adapterDirectories.add(target); }, write: async (target, value) => { adapterFiles.set(target, String(value)); }, read: async target => { if (!adapterFiles.has(target)) throw new Error('missing'); return String(adapterFiles.get(target)); }, writeBinary: async (target, value) => { adapterFiles.set(target, value.slice(0)); }, readBinary: async target => { if (!adapterFiles.has(target)) throw new Error('missing'); const value = adapterFiles.get(target); return value.slice(0); }, rename: async (from, to) => { adapterFiles.set(to, adapterFiles.get(from)); adapterFiles.delete(from); }, remove: async target => { adapterFiles.delete(target); } };
const bootstrapMeta = [{ file: 'A.md', heading: 'A', text: 'Mobile passage', contentHash: 'hash-a', passageVersion: 3 }], bootstrapVector = vector(1, 0), bootstrapManifest = await writeMobileBootstrap(memoryAdapter, '.obsidian/plugins/gib-search/mobile-bootstrap', { meta: bootstrapMeta, vectors: [bootstrapVector], dimension: 384, modelId: 'Xenova/bge-small-en-v1.5', passageVersion: 3, chunkCharacters: 1000 }), bootstrapRead = await readMobileBootstrap(memoryAdapter, '.obsidian/plugins/gib-search/mobile-bootstrap');
assert.equal(bootstrapRead.manifest.generation, bootstrapManifest.generation); assert.deepEqual(bootstrapRead.meta, bootstrapMeta); assert.equal(bootstrapRead.vectors[0][0], 1, 'Mobile bootstrap vector did not survive compression');
const corruptPath = `.obsidian/plugins/gib-search/mobile-bootstrap/${bootstrapManifest.segments[0].name}`, corrupt = new Uint8Array(adapterFiles.get(corruptPath)); corrupt[0] ^= 255; adapterFiles.set(corruptPath, corrupt.buffer); await assert.rejects(readMobileBootstrap(memoryAdapter, '.obsidian/plugins/gib-search/mobile-bootstrap'), /validation/, 'A corrupt synced bootstrap segment was accepted');

const bootstrapFile = { path: 'Synced.md', extension: 'md', stat: { mtime: 9, ctime: 1 } }, changedFile = { path: 'Changed.md', extension: 'md', stat: { mtime: 10, ctime: 1 } }, bootstrapContents = new Map([['Synced.md', '# Synced\nCurrent text'], ['Changed.md', '# Changed\nNewer mobile text']]), bootstrapPlugin = { isMobile: true, atlasEnabled: false, settings: { enabled: true, mobileBootstrapEnabled: true, mobileBootstrapPath: '' }, manifest: { id: 'gib-search' }, recordActivity() {}, logDiagnostic() {}, app: { vault: { adapter: { getBasePath: () => 'bootstrap-import-test' }, configDir: '.obsidian', getName: () => 'bootstrap-import-test', getFiles: () => [bootstrapFile, changedFile], read: async file => bootstrapContents.get(file.path) }, metadataCache: { getFileCache: () => ({ frontmatter: {} }) } } }, bootstrapRuntime = new MobileSearchRuntime(bootstrapPlugin); bootstrapRuntime.enabled = true; bootstrapRuntime.indexingTurn = async () => {}; bootstrapRuntime.saveIndex = async () => {}; const syncedEntry = await bootstrapRuntime.materializeMobileBootstrapFile(bootstrapFile), syncedReplacement = bootstrapRuntime.bootstrapReplacement(syncedEntry, syncedEntry.chunks.map(() => vector(1, 0))), staleEntry = await bootstrapRuntime.materializeMobileBootstrapFile(changedFile), staleReplacement = bootstrapRuntime.bootstrapReplacement({ ...staleEntry, representationHash: 'stale-package-hash' }, staleEntry.chunks.map(() => vector(0, 1))); bootstrapRuntime.meta = [{ file: 'Changed.md', heading: 'Local', text: 'Newer mobile text', contentHash: staleEntry.representationHash, passageVersion: 3, highlightVersion: 1, highlightCandidates: [], graphVersion: 1, entities: [] }]; bootstrapRuntime.vectors = [vector(0, 1)];
await bootstrapRuntime.importMobileBootstrap({ manifest: { generation: 'test-generation', modelId: 'Xenova/bge-small-en-v1.5', dimension: 384, passageVersion: 3, chunkCharacters: 1000, records: syncedReplacement.meta.length + staleReplacement.meta.length, createdAt: Date.now() }, meta: [...syncedReplacement.meta, ...staleReplacement.meta], vectors: [...syncedReplacement.vectors, ...staleReplacement.vectors] });
assert.ok(bootstrapRuntime.meta.some(item => item.file === 'Synced.md' && item.text.includes('Current text')), 'A current synced bootstrap note was not imported'); assert.ok(bootstrapRuntime.meta.some(item => item.file === 'Changed.md' && item.contentHash === staleEntry.representationHash), 'A stale package overwrote newer mobile progress');

const lexical = new IncrementalBm25();
lexical.replaceFile('Science.md', [{ key: 'science:1', fields: { title: 'Plant notes', heading: 'Energy', body: 'Photosynthesis converts light into chemical energy.', path: 'Study', metadata: 'biology' }, payload: { file: 'Science.md' } }]);
lexical.replaceFile('Journal.md', [{ key: 'journal:1', fields: { title: 'Daily entry', body: 'A quiet walk before breakfast.', path: 'Journal' }, payload: { file: 'Journal.md' } }]);
assert.equal(lexical.search('photosynthesis', 5)[0]?.key, 'science:1', 'BM25 did not recover an exact body term');
lexical.replaceFile('Science.md', [{ key: 'science:2', fields: { title: 'Plant notes', body: 'Roots take up water.' }, payload: { file: 'Science.md' } }]);
assert.equal(lexical.search('photosynthesis', 5).length, 0, 'Incremental BM25 retained a replaced passage');
assert.equal(lexical.search('breakfast', 5, new Set(['Science.md'])).length, 0, 'BM25 ignored a pre-ranking file scope');

const inFilePlugin = { isMobile: true, settings: {}, manifest: { id: 'gib-search' }, recordActivity() {}, logDiagnostic() {}, reportOnce() {}, app: { vault: { adapter: { getBasePath: () => 'in-file-test' }, configDir: '.obsidian', getName: () => 'in-file-test' }, metadataCache: { getFileCache: () => ({ frontmatter: {} }) }, workspace: { getActiveFile: () => null } } }, inFileRuntime = new MobileSearchRuntime(inFilePlugin); inFileRuntime.meta = [{ file: 'Target.md', heading: 'Concept', text: 'Plants capture sunlight and convert it into stored chemical energy.', lineStart: 0, lineEnd: 2 }, { file: 'Target.md', heading: 'Exact wording', text: 'The word photosynthesis appears in this separate passage.', lineStart: 10, lineEnd: 12 }, { file: 'Other.md', heading: 'Outside scope', text: 'Photosynthesis must not leak in from another file.', lineStart: 0, lineEnd: 1 }]; inFileRuntime.vectors = [vector(1, 0), vector(0, 1), vector(0, 1)]; inFileRuntime.queryVector = async () => vector(1, 0); inFileRuntime.refreshLexical(); const inFileResults = await inFileRuntime.search('photosynthesis', 10, .2, { file: 'Target.md', scoreWindow: 1 });
assert.equal(inFileResults.length, 2, 'Hybrid in-file search did not return both semantic and lexical passages'); assert.ok(inFileResults.every(result => result.file === 'Target.md'), 'In-file search leaked a passage from outside its pre-ranking file scope'); assert.ok(inFileResults.some(result => result.semanticScore > .9 && !/photosynthesis/i.test(result.text)), 'In-file search lost the meaning-based passage'); assert.ok(inFileResults.some(result => result.lexicalBoost > 0 && /photosynthesis/i.test(result.text)), 'In-file search lost the lexical passage');
const sentenceRuntime = new MobileSearchRuntime(inFilePlugin); sentenceRuntime.embedHighlightCandidates = async groups => groups.map(group => group.map(candidate => { const result = new Int16Array(384), sentenceFalsePositive = candidate.phrase.length > 80 && /truths to be known/i.test(candidate.phrase); result[/further study/i.test(candidate.phrase) || sentenceFalsePositive ? 0 : 1] = 32767; return result; })); const sentenceResults = [{ file: 'Target.md', semanticScore: .72, text: 'A weather report is incidental. *From further study, I have noticed that the question deserves attention.*' }, { file: 'Target.md', semanticScore: .7, text: 'There are undoubtedly many truths to be known, but only a few are relevant enough to our circumstances to be made known.' }]; await sentenceRuntime.semanticPassageHighlights(sentenceResults, vector(1, 0), { resultMinScore: .3, passageMinScore: .43, localPhraseMinScore: .58, sentenceFallbackMinScore: .57, sentenceFallbackLimit: 2, passageResultWindow: .18, passageResultLimit: 6, passageSentenceLimit: 8 }); assert.equal(sentenceResults[0].semanticPhrases?.[0]?.phrase.toLowerCase(), 'further study', 'Local semantic refinement did not prefer “further study” for the query concept “more study”'); assert.equal(sentenceResults[0].semanticPassages?.length, 0, 'A broad sentence fallback crowded out a stronger local semantic phrase'); assert.equal(sentenceResults[1].semanticPassages?.length, 0, 'A weak sentence fallback survived even though the query had a strong local phrase elsewhere');

const clauseSentence = 'Natural selection changes populations over time, but it does not explain why moral obligations bind rational persons.', clauseUnits = semanticClauseCandidates({ sourcePhrase: clauseSentence, phrase: clauseSentence, sentenceId: 3 }); assert.equal(clauseUnits.length, 2, 'A clear coordinated sentence was not divided into two conservative clauses'); assert.equal(clauseUnits[1].sourcePhrase, 'but it does not explain why moral obligations bind rational persons.', 'Clause refinement lost the exact source span');
const doctrinePassage = 'Organic evolution proceeds through natural processes to present perfection through the direction and power of God. Man is the divine offspring of God. God does not convey truth to my soul.', doctrineWindows = queryTermWindowCandidates(doctrinePassage, 'gods power'); assert.equal(doctrineWindows[0]?.sourcePhrase, 'power of God', 'Reordered and possessive query terms did not recover the obvious compact source phrase'); assert.ok(doctrineWindows.every(candidate => !/offspring|convey truth/i.test(candidate.sourcePhrase)), 'A partial topical overlap was mistaken for a complete query-term window');
const doctrineRuntime = new MobileSearchRuntime(inFilePlugin); doctrineRuntime.querySpecificity = async () => ({ anchors: ['god', 'power'], vectors: [vector(0, 1), vector(0, 1)] }); doctrineRuntime.embedHighlightCandidates = async groups => groups.map(group => group.map(candidate => { const result = new Int16Array(384), phrase = candidate.phrase.toLowerCase(), score = /power of god/.test(phrase) ? .88 : /offspring of god/.test(phrase) ? .66 : /convey truth/.test(phrase) ? .6 : .64; result[0] = Math.round(score * 32767); return result; })); const doctrineResults = [{ file: 'Doctrine.md', semanticScore: .35, text: 'Organic evolution proceeds through the direction and power of God.', lineStart: 1, lineEnd: 1 }, { file: 'Doctrine.md', semanticScore: .8, text: 'Man is the divine offspring of God.', lineStart: 2, lineEnd: 2 }, { file: 'Doctrine.md', semanticScore: .77, text: 'God does not convey truth to my soul.', lineStart: 3, lineEnd: 3 }]; await doctrineRuntime.semanticPassageHighlights(doctrineResults, vector(1, 0), { query: 'gods power', resultMinScore: .3, passageMinScore: .43, localPhraseMinScore: .58, clauseMinScore: .53, clauseParentMargin: .015, clauseContextWeight: .18, localSemanticLimit: 4, localSemanticWindow: .1, sentenceFallbackMinScore: .57, sentenceFallbackLimit: 2, passageResultWindow: .18, passageResultLimit: 6, passageSentenceLimit: 32 }); assert.equal(doctrineResults[0].semanticPhrases?.[0]?.sourcePhrase, 'power of God', 'An obvious full-term match was lost because its passage had a lower embedding score'); assert.equal(doctrineResults[1].semanticPhrases?.length, 0, 'A one-term topical overlap survived beside the complete concept match'); assert.equal(doctrineResults[2].semanticPhrases?.length, 0, 'An unrelated semantic phrase survived beside the complete concept match');
const relationRuntime = new MobileSearchRuntime(inFilePlugin); relationRuntime.querySpecificity = async () => ({ anchors: ['child', 'god'], vectors: [vector(0, 1, 0), vector(0, 0, 1)], modifiers: [], modifierVectors: [], allAnchors: ['child', 'god'] }); relationRuntime.embedHighlightCandidates = async groups => groups.map(group => group.map(candidate => { const result = new Int16Array(384), phrase = candidate.phrase.toLowerCase(), sentence = phrase.length > 42; let scores = [.4, .4, .4]; if (/offspring of god/.test(phrase)) scores = sentence ? [.61, .5, .55] : [.79, .56, .66]; else if (/correctly understood/.test(phrase)) scores = [.7, .45, .71]; else if (/say that god/.test(phrase)) scores = [.68, .53, .73]; scores.forEach((score, index) => { result[index] = Math.round(score * 32767); }); return result; })); const relationResult = { file: 'Relation.md', contentHash: 'relation-beam', semanticScore: .74, text: 'Humanity is described as the divine offspring of God. A speaker may say that God remains mysterious. God is correctly understood by the congregation.', lineStart: 1, lineEnd: 3 }; await relationRuntime.semanticPassageHighlights([relationResult], vector(1, 0, 0), { query: 'child of god', resultMinScore: .3, passageMinScore: .43, localPhraseMinScore: .58, clauseMinScore: .53, clauseParentMargin: .015, clauseContextWeight: .18, localSentenceBeam: 6, localSemanticLimit: 4, localSemanticWindow: .1, sentenceFallbackMinScore: .57, sentenceFallbackLimit: 2, passageResultWindow: .18, passageResultLimit: 6, passageSentenceLimit: 32 }); const relationPhrases = relationResult.semanticPhrases?.map(item => item.sourcePhrase) || []; assert.ok(relationPhrases.some(phrase => /offspring of God/i.test(phrase)), `Multi-sentence refinement missed a relational synonym outside the strongest sentence: ${JSON.stringify(relationPhrases)}`); assert.ok(relationPhrases.every(phrase => !/say that God|correctly understood/i.test(phrase)), `Entity-only fragments survived contrastive query scoring: ${JSON.stringify(relationPhrases)}`);
const clauseRuntime = new MobileSearchRuntime(inFilePlugin), clauseGroups = []; clauseRuntime.embedHighlightCandidates = async groups => { clauseGroups.push(groups.map(group => group.length)); return groups.map(group => group.map(candidate => { const result = new Int16Array(384), phrase = candidate.phrase.toLowerCase(), score = phrase === clauseSentence.toLowerCase() ? .56 : phrase.startsWith('but it does not explain why moral obligations') ? .91 : phrase.startsWith('natural selection changes populations') ? .46 : .2; result[0] = Math.round(score * 32767); return result; })); }; const clauseResult = { file: 'Target.md', contentHash: 'clause-fingerprint', semanticScore: .76, text: clauseSentence, lineStart: 4, lineEnd: 4 }; await clauseRuntime.semanticPassageHighlights([clauseResult], vector(1, 0), { resultMinScore: .3, passageMinScore: .43, localPhraseMinScore: .58, clauseMinScore: .53, clauseParentMargin: .015, clauseContextWeight: .18, localSemanticLimit: 4, localSemanticWindow: .1, sentenceFallbackMinScore: .57, sentenceFallbackLimit: 2, passageResultWindow: .18, passageResultLimit: 6, passageSentenceLimit: 32 }); assert.equal(clauseResult.semanticPhrases?.[0]?.kind, 'clause', 'A strong clause did not beat its weaker parent sentence'); assert.equal(clauseResult.semanticPhrases?.[0]?.sourcePhrase, clauseUnits[1].sourcePhrase, 'The selected clause did not preserve its exact highlight source'); assert.equal(clauseResult.semanticPassages?.length, 0, 'A whole-sentence fallback survived beside a stronger clause');
const cachedUnits = clauseRuntime.inFilePassageUnits(clauseResult, 32); assert.strictEqual(clauseRuntime.inFilePassageUnits(clauseResult, 32), cachedUnits, 'Unchanged passage units were reparsed instead of using the fingerprint cache'); const manySentences = { ...clauseResult, contentHash: 'many-sentences', text: Array.from({ length: 14 }, (_, index) => `Sentence ${index} explains a distinct indexed idea.`).join(' ') }, exhaustiveUnits = clauseRuntime.inFilePassageUnits(manySentences, 32); assert.equal(exhaustiveUnits.sentences.length, 14, 'In-file refinement still samples sentences instead of considering every sentence in the passage'); const boundedUnits = clauseRuntime.inFilePassageUnits({ ...manySentences, contentHash: 'bounded-sentences', text: Array.from({ length: 80 }, (_, index) => `Bounded sentence ${index} explains another indexed idea.`).join(' ') }, 32); assert.equal(boundedUnits.sentences.length, 32, 'Pathological passages can exceed the bounded interactive sentence workload'); assert.ok(clauseGroups[0]?.[0] >= 1, 'Hierarchical refinement did not embed sentence candidates'); clauseRuntime.commitIndex([], [], new Set(['Target.md'])); assert.equal(clauseRuntime.inFileUnitCache.size, 0, 'Changed-file indexing did not invalidate fingerprinted in-file units');
const cancellationRuntime = new MobileSearchRuntime(inFilePlugin); cancellationRuntime.liveGeneration = 2; cancellationRuntime.embedHighlightCandidates = clauseRuntime.embedHighlightCandidates; await assert.rejects(cancellationRuntime.semanticPassageHighlights([{ ...clauseResult }], vector(1, 0), { _liveGeneration: 1, resultMinScore: .3, passageMinScore: .43, passageSentenceLimit: 32 }), /Superseded by a newer semantic query/, 'A superseded hierarchical search continued into clause and phrase refinement');

const candidates = Array.from({ length: 5000 }, (_, index) => ({ id: index, score: Math.sin(index * 1.7) })), expected = candidates.slice().sort((a, b) => b.score - a.score).slice(0, 17).map(item => item.id), actual = boundedTopK(candidates, 17).map(item => item.id);
assert.deepEqual(actual, expected, 'Bounded top-K selection changed ranking order');

const multiTheme = diverseCentroids([vector(1, 0), vector(0, 1), vector(.98, .02), vector(.02, .98)], 3), sameThemes = diverseCentroids([vector(1, 0), vector(0, 1)], 3), genericMiddle = diverseCentroids([vector(1, 1), vector(1, 1)], 3);
assert.ok(centroidSimilarity(multiTheme, sameThemes) > centroidSimilarity(multiTheme, genericMiddle), 'Multi-centroid similarity collapsed a note into its average topic');

const validSegment = { meta: [{ file: 'A.md' }], vectors: vector(1, 0).buffer }, recovered = assembleIndexSegments([validSegment]); assert.equal(recovered.meta[0].file, 'A.md'); assert.equal(new Float32Array(recovered.vectors).length, 384); assert.throws(() => assembleIndexSegments([{ meta: [{ file: 'broken.md' }], vectors: new ArrayBuffer(4) }]), /incomplete/, 'A torn index segment was accepted instead of falling back to the prior generation');

const chunks = chunkMarkdown('---\ntitle: Hidden metadata\n---\n\n## First section\nVisible body text.\n\n## Last section\nClosing body text.', 700);
assert.equal(chunks[0]?.heading, 'First section'); assert.equal(chunks[0]?.lineStart, 5); assert.ok(chunks.every(chunk => !chunk.text.includes('Hidden metadata')), 'Chunking leaked frontmatter into passages'); assert.equal(chunks.at(-1)?.heading, 'Last section');

const highEndProfile = indexingHardwareProfile(false, 32, 16), modestProfile = indexingHardwareProfile(false, 4, 4), mobileProfile = indexingHardwareProfile(true, 12, 8);
assert.equal(highEndProfile.wasmThreads, 12); assert.equal(highEndProfile.maximumEmbedBatchSize, 16); assert.ok(modestProfile.wasmThreads < highEndProfile.wasmThreads && modestProfile.maximumEmbedBatchSize < highEndProfile.maximumEmbedBatchSize, 'Desktop indexing does not scale with available hardware'); assert.equal(mobileProfile.wasmThreads, 1); assert.equal(mobileProfile.maximumEmbedBatchSize, 1, 'Mobile indexing lost its strict single-passage safety profile');

const batchingPlugin = { isMobile: false, settings: {}, manifest: { id: 'gib-search' }, recordActivity() {}, logDiagnostic() {}, app: { vault: { adapter: { getBasePath: () => 'batch-test' }, configDir: '.obsidian', getName: () => 'batch-test' } } }, batchingRuntime = new MobileSearchRuntime(batchingPlugin), batchLengths = []; batchingRuntime.enabled = true; batchingRuntime.indexingConfig = { ...highEndProfile, maximumBatchCharacters: 100000 }; batchingRuntime.indexEmbedBatchSize = 8; batchingRuntime.indexingTurn = async () => {}; batchingRuntime.embedBatch = async texts => { batchLengths.push(texts.length); return texts.map(() => vector(1, 0)); };
assert.equal((await batchingRuntime.embedIndexChunks(Array.from({ length: 17 }, (_, index) => `passage ${index}`))).length, 17); assert.equal(batchLengths.reduce((sum, value) => sum + value, 0), 17); assert.equal(batchLengths[0], 8); assert.ok(batchLengths.every(value => value <= highEndProfile.maximumEmbedBatchSize) && batchLengths.some(value => value > 1), 'Desktop passages were not combined into bounded adaptive inference batches');
batchingRuntime.workerRuntimeProfile({ backend: 'webgpu', dtype: 'fp16', maximumEmbedBatchSize: 16 }); assert.equal(batchingRuntime.modelBackend, 'web-worker-webgpu'); assert.equal(batchingRuntime.indexEmbedBatchSize, 16); assert.ok(batchingRuntime.indexingConfig.maximumEmbedBatchSize <= 16, 'WebGPU indexing batch lost its bounded ceiling');

const files = new Map([['A.md', { path: 'A.md', extension: 'md', stat: { mtime: 2, ctime: 1 } }]]), reads = [];
const plugin = { isMobile: true, settings: { writingProfileIndexEnabled: false }, manifest: { id: 'gib-search' }, recordActivity() {}, logDiagnostic() {}, reportOnce() {}, app: { vault: { adapter: { getBasePath: () => 'test' }, configDir: '.obsidian', getName: () => 'test', getFiles: () => { throw new Error('dirty-file indexing performed a vault-wide scan'); }, getAbstractFileByPath: file => files.get(file) || null, read: async file => { reads.push(file.path); return '# Updated\nOnly this file changed.'; } }, metadataCache: { getFileCache: () => ({ frontmatter: {} }) }, workspace: { getActiveFile: () => null } } };
const runtime = new MobileSearchRuntime(plugin); runtime.enabled = true; runtime.indexingTurn = async () => {}; runtime.embedIndexChunks = async texts => texts.map(() => vector(1, 0)); runtime.queueIndexSave = () => { runtime.indexDirty = true; }; runtime.scheduleWritingProfileSync = () => {}; runtime.meta = [{ file: 'A.md', heading: 'Old', text: 'Old text', lineStart: 0, lineEnd: 0, mtime: 1, contentHash: 'old-a', passageVersion: 3, highlightVersion: 1, highlightCandidates: [], graphVersion: 1, entities: [] }, { file: 'B.md', heading: '', text: 'Untouched', lineStart: 0, lineEnd: 0, mtime: 1, contentHash: 'old-b', passageVersion: 3, highlightVersion: 1, highlightCandidates: [], graphVersion: 1, entities: [] }]; runtime.vectors = [vector(1, 0), vector(0, 1)];
await runtime.performDirtyIndexUpdate(false, new Set(['A.md']));
assert.deepEqual(reads, ['A.md'], 'Dirty-file indexing read more than the changed file'); assert.ok(runtime.meta.some(item => item.file === 'B.md' && item.text === 'Untouched'), 'Dirty-file commit discarded an unchanged note'); assert.ok(runtime.meta.some(item => item.file === 'A.md' && item.text.includes('Only this file changed')), 'Dirty-file commit did not replace the changed note');

const checkpointFiles = Array.from({ length: 12 }, (_, index) => ({ path: `Checkpoint-${index}.md`, extension: 'md', stat: { mtime: index + 1, ctime: 1 } })), checkpointPlugin = { isMobile: false, atlasEnabled: false, settings: { writingProfileIndexEnabled: false }, manifest: { id: 'gib-search' }, recordActivity() {}, logDiagnostic() {}, reportOnce() {}, app: { vault: { adapter: { getBasePath: () => 'checkpoint-test' }, configDir: '.obsidian', getName: () => 'checkpoint-test', getFiles: () => checkpointFiles, read: async file => `# ${file.path}\nCheckpointed content.` }, metadataCache: { getFileCache: () => ({ frontmatter: {} }) }, workspace: { getActiveFile: () => null } }, desktopEmbedder: { embedBatch: async texts => texts.map(() => vector(1, 0)) } }, checkpointRuntime = new MobileSearchRuntime(checkpointPlugin); let checkpointCount = 0; checkpointRuntime.enabled = true; checkpointRuntime.indexingConfig = { ...highEndProfile, maximumEmbedBatchSize: 4, maximumBatchCharacters: 100000, checkpointFiles: 4, checkpointMs: 60000 }; checkpointRuntime.indexEmbedBatchSize = 4; checkpointRuntime.indexingTurn = async () => {}; checkpointRuntime.queueIndexSave = () => { checkpointRuntime.indexDirty = true; }; checkpointRuntime.saveIndex = async () => { checkpointCount++; checkpointRuntime.indexDirty = false; checkpointRuntime.cancelRequested = true; }; checkpointRuntime.scheduleWritingProfileSync = () => {};
await checkpointRuntime.performDirtyIndexUpdate(true); assert.equal(checkpointCount, 1, 'Long rebuild did not create a resumable checkpoint'); assert.equal(new Set(checkpointRuntime.meta.map(item => item.file)).size, 4, 'Completed files were not committed before an interrupted rebuild');

const emptyFile = { path: 'Empty.md', extension: 'md', stat: { mtime: 1, ctime: 1 } }; let emptyReads = 0; const emptyPlugin = { ...checkpointPlugin, app: { ...checkpointPlugin.app, vault: { ...checkpointPlugin.app.vault, getFiles: () => [emptyFile], getAbstractFileByPath: () => emptyFile, read: async () => { emptyReads++; return ''; } } } }, emptyRuntime = new MobileSearchRuntime(emptyPlugin); emptyRuntime.enabled = true; emptyRuntime.indexingTurn = async () => {}; emptyRuntime.queueIndexSave = () => { emptyRuntime.indexDirty = true; }; emptyRuntime.scheduleWritingProfileSync = () => {};
await emptyRuntime.performDirtyIndexUpdate(false, new Set(['Empty.md'])); await emptyRuntime.performDirtyIndexUpdate(false, new Set(['Empty.md'])); assert.equal(emptyReads, 1, 'An unchanged empty note was repeatedly reread'); assert.ok(emptyRuntime.meta.some(item => item.file === 'Empty.md' && item.text === '' && !item.filenameOnly), 'Empty Markdown note did not receive a stable searchable index record');

const runtimeSource = fs.readFileSync(path.join(root, 'src', 'mobile-runtime.js'), 'utf8'), workerSource = fs.readFileSync(path.join(root, 'src', 'desktop-embed-worker.js'), 'utf8'), mainSource = fs.readFileSync(path.join(root, 'src', 'main.js'), 'utf8');
assert.ok(runtimeSource.includes('const INDEX_BUCKETS = 64') && runtimeSource.includes(':segment:${snapshot.buckets[bucket]}') && runtimeSource.includes('previousManifest.current'), 'Mobile persistence is not segmented with a rollback generation');
assert.ok(workerSource.includes('const taskQueues = Array.from') && workerSource.includes('enqueueTask(message.priority') && workerSource.includes("enqueueTask(message.lowPriority ? 4 : 2") && workerSource.includes('serviceHigherPriorityTasks(4)'), 'Background inference does not prioritize or cooperatively admit interactive work');
assert.ok(workerSource.includes('configuration?.wasmThreads') && workerSource.includes("loadEmbeddingModel('webgpu', dtype)") && workerSource.includes('activateWasm(error)') && runtimeSource.includes('maximumEmbedBatchSize') && runtimeSource.includes('commitMaterializedIndexEntries(materialized)'), 'Desktop inference is not hardware-adaptive, GPU-accelerated with fallback, or does not batch passages across notes');
assert.ok(mainSource.includes('semanticHighlights: false') && mainSource.includes('highlightResults(highlighted, query'), 'Search does not render results before semantic highlighting');
assert.ok(!runtimeSource.includes("from 'compromise'"), 'The synchronous NLP parser remains in the indexing runtime');

const performanceIndex = new IncrementalBm25(); for (let index = 0; index < 12000; index++) performanceIndex.upsert(`doc:${index}`, { title: `Note ${index}`, body: `shared language topic-${index % 97} exact-${index}` }, { file: `${index}.md` }); const started = performance.now(); const performanceResults = performanceIndex.search('shared language', 20); const elapsed = performance.now() - started; assert.equal(performanceResults.length, 20); assert.ok(elapsed < 750, `BM25 performance regression: ${elapsed.toFixed(1)} ms`);

console.log(`Search engine checks passed (${elapsed.toFixed(1)} ms for 12,000-document lexical retrieval).`);
