import { EMOTION_LANDMARKS, TEXT_SIGNALS, validTextSignal } from './text-signals.js';

const INDEXABLE = /\.(?:md|txt|markdown)$/i;

export const DEFAULT_ATLAS_VIEW = {
  id: 'all-notes',
  name: 'Meaning',
  scope: { match: 'all', rules: [], folders: [], excludeFolders: [], tags: [], properties: {}, extensions: ['md', 'txt', 'markdown'] },
  anchor: { type: 'default' },
  scale: 'default',
  frame: { mode: 'natural', referenceFrame: 'free', signal: 'semantic', reference: '', geometry: 'semantic', relationships: { semantic: 1, emotion: 0, purpose: 0, position: 0, form: 0, links: 0 }, anchors: [], dynamics: { contrast: .58, cohesion: .62, spacing: .55, spring: .68, charge: .56, selectivity: .45, mutuality: .7, bridges: .42, settling: .68, containment: .62, physicsRate: .5 }, environment: { collision: .7, charge: .56, containment: .62, damping: .72, physicsRate: .5 }, categoryPull: .78, localCohesion: .26, sensitivity: .58, unclaimedThreshold: .34, appearance: { colorBy: 'semantic', sizeBy: 'file', terrain: 'density', regions: false, labels: false, linkLines: false }, visuals: [], categories: [] },
};

export const ATLAS_VIEW_TEMPLATES = {
  meaning: { id: 'all-notes', name: 'Meaning', signal: 'semantic', relationships: { semantic: 1 }, description: 'See the vault by similarity of ideas.', categories: [] },
  topics: { id: 'topics', name: 'Topics', signal: 'semantic', relationships: { semantic: 1 }, description: 'Reveal local topic neighborhoods and their boundaries.', categories: [] },
  emotion: { id: 'emotion', name: 'Emotion', signal: 'emotion', relationships: { emotion: 1 }, description: 'See writing by its expressed emotional character.', categories: [] },
  purpose: { id: 'purpose', name: 'Purpose', signal: 'purpose', relationships: { purpose: 1 }, description: 'Group writing by what it is trying to do.', categories: [] },
  form: { id: 'form', name: 'Writing form', signal: 'form', relationships: { form: 1 }, description: 'Separate journals, essays, conversations, references, narratives, and plans.', categories: [] },
  links: { id: 'links', name: 'Links', signal: 'semantic', relationships: { semantic: .12, links: 1 }, description: 'Let authored links provide the primary structure.', categories: [] },
};

export const STANDARD_ATLAS_VIEWS = Object.values(ATLAS_VIEW_TEMPLATES).map(template => ({
  ...copy(DEFAULT_ATLAS_VIEW),
  id: template.id,
  name: template.name,
  description: template.description,
  frame: {
    ...copy(DEFAULT_ATLAS_VIEW.frame),
    signal: template.signal,
    relationships: { semantic: 0, emotion: 0, purpose: 0, position: 0, form: 0, links: 0, ...template.relationships },
    appearance: { ...copy(DEFAULT_ATLAS_VIEW.frame.appearance), colorBy: template.signal === 'emotion' ? 'emotion' : 'semantic', terrain: template.signal === 'emotion' ? 'intensity' : 'density', regions: template.id === 'topics', labels: template.id === 'topics', linkLines: template.id === 'links' },
  },
}));

export function validAtlasScale(value) { return ['overview', 'neighborhood', 'detail'].includes(value) ? value : 'overview'; }

function normalizedPath(value) { return String(value || '').replaceAll('\\', '/').replace(/^\/+|\/+$/g, ''); }
function pathWithin(path, folder) { const normalized = normalizedPath(folder); return !normalized || path === normalized || path.startsWith(`${normalized}/`); }
function edgeKey(a, b) { return [a, b].sort().join('\0'); }
function basename(file) { return String(file || '').split('/').pop().replace(INDEXABLE, ''); }
function stableSignature(value) { let hash = 2166136261; for (const character of String(value || '')) { hash ^= character.codePointAt(0); hash = Math.imul(hash, 16777619); } return (hash >>> 0).toString(36); }
function copy(value) { return value == null ? value : JSON.parse(JSON.stringify(value)); }
function clamp(value, low = 0, high = 1) { return Math.max(low, Math.min(high, Number(value) || 0)); }
function vectorDot(first, second) { let value = 0; for (let index = 0; index < Math.min(first?.length || 0, second?.length || 0); index++) value += first[index] * second[index]; return value; }
function percentile(values, amount) { if (!values.length) return 0; const ordered = values.slice().sort((a, b) => a - b), position = clamp(amount) * (ordered.length - 1), lower = Math.floor(position), upper = Math.ceil(position), blend = position - lower; return ordered[lower] * (1 - blend) + ordered[upper] * blend; }
function normalizeCategory(category, index) { const name = String(category?.name || `Category ${index + 1}`).trim(), position = category?.position || {}; return { id: String(category?.id || stableSignature(`${name}:${index}`)), key: String(category?.key || '').trim(), modelLabel: String(category?.modelLabel || '').trim().toLowerCase(), name, description: String(category?.description || '').trim(), keywords: (category?.keywords || []).map(value => String(value).trim()).filter(Boolean), examples: (category?.examples || []).map(normalizedPath).filter(Boolean), weight: clamp(category?.weight ?? 1, .1, 2), position: Number.isFinite(Number(position.x)) && Number.isFinite(Number(position.y)) ? { x: clamp(position.x, -.9, .9), y: clamp(position.y, -.9, .9) } : null }; }
function normalizeRelationships(value, legacySignal = 'semantic') { const source = value && typeof value === 'object' ? value : { [legacySignal]: 1 }, output = {}; for (const id of Object.keys(TEXT_SIGNALS)) output[id] = clamp(typeof source[id] === 'object' ? source[id].weight : source[id] ?? 0); if (!Object.values(output).some(weight => weight > 0)) output.semantic = 1; return output; }
function normalizeDynamics(value = {}) { return { contrast: clamp(value.contrast ?? .58), cohesion: clamp(value.cohesion ?? .62), spacing: clamp(value.spacing ?? .55), spring: clamp(value.spring ?? .68), charge: clamp(value.charge ?? .56), selectivity: clamp(value.selectivity ?? .45), mutuality: clamp(value.mutuality ?? .7), bridges: clamp(value.bridges ?? .42), settling: clamp(value.settling ?? .68), containment: clamp(value.containment ?? .62), physicsRate: clamp(value.physicsRate ?? .5) }; }
function normalizeScopeRule(rule = {}) { return { id: String(rule.id || stableSignature(JSON.stringify(rule))), field: ['folder', 'path', 'name', 'extension', 'tag', 'property', 'linksTo', 'linkedFrom', 'size', 'created', 'modified'].includes(rule.field) ? rule.field : 'folder', operator: ['is', 'isNot', 'contains', 'notContains', 'startsWith', 'endsWith', 'exists', 'notExists', 'greater', 'less'].includes(rule.operator) ? rule.operator : 'contains', key: String(rule.key || '').trim(), value: String(rule.value ?? '').trim() }; }
function normalizeAnchor(anchor = {}, index = 0) { const label = String(anchor.label || anchor.name || anchor.anchor || '').trim(); return { id: String(anchor.id || stableSignature(`${label}:${index}`)), label, description: String(anchor.description || label).trim(), signal: validTextSignal(anchor.signal || anchor.source), strength: clamp(anchor.strength ?? anchor.weight ?? .7) }; }
function normalizeVisual(rule = {}) { return { id: String(rule.id || stableSignature(JSON.stringify(rule))), source: Object.keys(TEXT_SIGNALS).includes(rule.source) || ['fileSize', 'density', 'relationship', 'community', 'links'].includes(rule.source) ? rule.source : 'semantic', channel: ['color', 'size', 'elevation', 'regions', 'labels', 'lines'].includes(rule.channel) ? rule.channel : 'color', enabled: rule.enabled !== false }; }
function compareRule(actual, operator, expected) { const values = Array.isArray(actual) ? actual.map(String) : [String(actual ?? '')], wanted = String(expected ?? ''), lower = wanted.toLowerCase(), matches = value => { const text = value.toLowerCase(); if (operator === 'is') return text === lower; if (operator === 'isNot') return text !== lower; if (operator === 'contains') return text.includes(lower); if (operator === 'notContains') return !text.includes(lower); if (operator === 'startsWith') return text.startsWith(lower); if (operator === 'endsWith') return text.endsWith(lower); if (operator === 'exists') return text.length > 0; if (operator === 'notExists') return text.length === 0; if (operator === 'greater') return Number(value) > Number(wanted); if (operator === 'less') return Number(value) < Number(wanted); return false; }; return operator === 'isNot' || operator === 'notContains' || operator === 'notExists' ? values.every(matches) : values.some(matches); }
function categoryAnchorLayout(categories, vectors, geometry) {
  const count = categories.length, radial = categories.map((category, index) => { const angle = -Math.PI / 2 + index / count * Math.PI * 2; return { ...category, angle, x: Math.cos(angle) * .68, y: Math.sin(angle) * .68, hue: (index * 360 / count + 282) % 360 }; });
  if (geometry === 'radial') return radial;
  if (geometry === 'manual') return radial.map(anchor => ({ ...anchor, x: anchor.position?.x ?? anchor.x, y: anchor.position?.y ?? anchor.y }));
  const points = radial.map(anchor => ({ ...anchor }));
  for (let iteration = 0; iteration < 180; iteration++) {
    const velocity = points.map(() => ({ x: 0, y: 0 }));
    for (let first = 0; first < count; first++) for (let second = first + 1; second < count; second++) { const a = points[first], b = points[second], similarity = clamp((vectorDot(vectors[first], vectors[second]) + 1) / 2), desired = .3 + Math.sqrt(1 - similarity) * .78; let dx = b.x - a.x, dy = b.y - a.y, distance = Math.max(.02, Math.hypot(dx, dy)), force = (distance - desired) * .035; if (distance < .22) force -= (.22 - distance) * .08; dx /= distance; dy /= distance; velocity[first].x += dx * force; velocity[first].y += dy * force; velocity[second].x -= dx * force; velocity[second].y -= dy * force; }
    for (let index = 0; index < count; index++) { velocity[index].x -= points[index].x * .006; velocity[index].y -= points[index].y * .006; points[index].x += velocity[index].x * .76; points[index].y += velocity[index].y * .76; }
  }
  const meanX = points.reduce((sum, point) => sum + point.x, 0) / count, meanY = points.reduce((sum, point) => sum + point.y, 0) / count, extent = Math.max(.001, ...points.map(point => Math.hypot(point.x - meanX, point.y - meanY))); for (const point of points) { point.x = (point.x - meanX) / extent * .72; point.y = (point.y - meanY) / extent * .72; point.angle = Math.atan2(point.y, point.x); }
  return points;
}

function fileScales(app) {
  const files = app.vault.getFiles().filter(file => INDEXABLE.test(file.path)), sizes = files.map(file => Math.log1p(Number(file.stat?.size || 0))), low = sizes.length ? Math.min(...sizes) : 0, high = sizes.length ? Math.max(...sizes) : 1, spread = Math.max(.001, high - low);
  return new Map(files.map(file => [file.path, (Math.log1p(Number(file.stat?.size || 0)) - low) / spread]));
}

function manualLinks(app, files) {
  const visible = new Set(files || []), roads = new Map(), resolved = app?.metadataCache?.resolvedLinks || {};
  for (const source of visible) for (const [target, count] of Object.entries(resolved[source] || {})) { if (!count || source === target || !visible.has(target)) continue; const [first, second] = [source, target].sort(), key = edgeKey(first, second), road = roads.get(key) || { key, source: first, target: second, forward: false, reverse: false, count: 0 }; if (source === first) road.forward = true; else road.reverse = true; road.count += Number(count || 0); roads.set(key, road); }
  return [...roads.values()];
}

function cloneScene(scene) {
  return { ...scene, state: copy(scene.state), center: { ...scene.center }, nodes: scene.nodes.map(node => ({ ...node })), edges: scene.edges.map(edge => ({ ...edge })), roads: scene.roads.map(road => ({ ...road })), results: scene.results.map(result => ({ ...result })), legend: scene.legend.map(item => ({ ...item })) };
}

export class AtlasEngine {
  constructor(plugin) { this.plugin = plugin; this.sceneCache = new Map(); this.context = { surface: 'note', state: null, query: '', results: [], loading: false, selection: null, hover: null }; this.contextListeners = new Set(); }

  publishContext(next = {}) { this.context = { ...this.context, ...next }; for (const listener of this.contextListeners) listener(this.context); }
  subscribeContext(listener) { this.contextListeners.add(listener); listener(this.context); return () => this.contextListeners.delete(listener); }

  views() {
    const configured = Array.isArray(this.plugin.settings?.atlasViews) ? this.plugin.settings.atlasViews : [], byId = new Map(STANDARD_ATLAS_VIEWS.map(view => [view.id, this.normalizeView(view)]));
    for (const view of configured) byId.set(String(view.id || ''), this.normalizeView(view));
    return [...byId.values()];
  }

  normalizeView(view = {}) {
    const scope = view.scope || {}, extensions = Array.isArray(scope.extensions) && scope.extensions.length ? scope.extensions.map(value => String(value).toLowerCase().replace(/^\./, '')) : DEFAULT_ATLAS_VIEW.scope.extensions, frame = view.frame || {}, legacyMode = frame.mode === 'guided' ? 'constellation' : view.anchor?.type === 'query' ? 'center' : 'free', referenceFrame = ['free', 'center', 'constellation', 'axis'].includes(frame.referenceFrame) ? frame.referenceFrame : legacyMode, migratedWeights = { ...(frame.relationships || {}) }; for (const rule of frame.forces || []) if (TEXT_SIGNALS[rule.source] && !['collision', 'charge', 'containment', 'flow'].includes(rule.force)) migratedWeights[rule.source] = Math.max(Number(migratedWeights[rule.source] || 0), Number(rule.strength || 0)); const relationships = normalizeRelationships(migratedWeights, validTextSignal(frame.signal)), dynamics = normalizeDynamics(frame.dynamics), environment = { collision: clamp(frame.environment?.collision ?? .7), charge: clamp(frame.environment?.charge ?? dynamics.charge), containment: clamp(frame.environment?.containment ?? dynamics.containment), damping: clamp(frame.environment?.damping ?? .72), physicsRate: clamp(frame.environment?.physicsRate ?? dynamics.physicsRate) }, migratedAnchors = frame.anchors?.length ? frame.anchors : (frame.forces || []).filter(rule => ['gravity', 'axis'].includes(rule.force) && String(rule.anchor || '').trim()).map(rule => ({ id: rule.id, label: rule.anchor, description: rule.anchor, signal: rule.source, strength: rule.strength })), anchors = migratedAnchors.map(normalizeAnchor).filter(anchor => anchor.label).slice(0, 12), categories = anchors.length ? anchors.map(anchor => ({ id: `anchor:${anchor.id}`, name: anchor.label, description: anchor.description, keywords: [], examples: [], weight: anchor.strength, position: null })) : (frame.categories || []).map(normalizeCategory).filter(category => category.name).slice(0, 12), visuals = (frame.visuals?.length ? frame.visuals : [{ source: frame.appearance?.colorBy === 'emotion' ? 'emotion' : 'semantic', channel: 'color' }, { source: frame.appearance?.sizeBy === 'uniform' ? 'semantic' : 'fileSize', channel: 'size' }, { source: frame.appearance?.terrain === 'intensity' ? 'relationship' : 'density', channel: 'elevation', enabled: frame.appearance?.terrain !== 'off' }, { source: 'community', channel: 'regions', enabled: frame.appearance?.regions === true }, { source: 'community', channel: 'labels', enabled: frame.appearance?.labels === true }, { source: 'links', channel: 'lines', enabled: frame.appearance?.linkLines === true }]).map(normalizeVisual);
    return {
      id: String(view.id || stableSignature(view.name || 'all-notes')),
      name: String(view.name || 'All Notes'),
      description: String(view.description || '').trim(),
      scope: { match: scope.match === 'any' ? 'any' : 'all', rules: (scope.rules || []).map(normalizeScopeRule), folders: (scope.folders || []).map(normalizedPath).filter(Boolean), excludeFolders: (scope.excludeFolders || []).map(normalizedPath).filter(Boolean), tags: (scope.tags || []).map(tag => String(tag).replace(/^#/, '')).filter(Boolean), properties: { ...(scope.properties || {}) }, extensions },
      anchor: view.anchor && typeof view.anchor === 'object' ? { ...view.anchor } : { type: 'default' },
      scale: view.scale === 'default' ? 'default' : validAtlasScale(view.scale),
      frame: { mode: anchors.length || categories.length && ['constellation', 'axis'].includes(referenceFrame) ? 'guided' : 'natural', referenceFrame: anchors.length ? 'constellation' : referenceFrame, signal: anchors[0]?.signal || validTextSignal(frame.signal), reference: String(frame.reference || '').trim(), geometry: ['semantic', 'radial', 'manual'].includes(frame.geometry) ? frame.geometry : 'semantic', relationships, anchors, dynamics: { ...dynamics, charge: environment.charge, containment: environment.containment, physicsRate: environment.physicsRate }, environment, categoryPull: clamp(frame.categoryPull ?? .78), localCohesion: clamp(frame.localCohesion ?? .26), sensitivity: clamp(frame.sensitivity ?? .58), unclaimedThreshold: clamp(frame.unclaimedThreshold ?? .34), appearance: { colorBy: ['category', 'semantic', 'emotion', 'relationship', 'none'].includes(frame.appearance?.colorBy) ? frame.appearance.colorBy : anchors.length ? 'category' : 'semantic', sizeBy: frame.appearance?.sizeBy === 'uniform' ? 'uniform' : 'file', terrain: ['density', 'intensity', 'off'].includes(frame.appearance?.terrain) ? frame.appearance.terrain : 'density', regions: frame.appearance?.regions === true, labels: frame.appearance?.labels === true, linkLines: frame.appearance?.linkLines === true }, visuals, categories },
    };
  }

  activeView(id = this.plugin.settings?.atlasHomeViewId) { return this.views().find(view => view.id === id) || this.views()[0] || this.normalizeView(DEFAULT_ATLAS_VIEW); }

  state(overrides = {}) {
    const view = this.normalizeView(overrides.view || this.activeView(overrides.viewId)), scale = validAtlasScale(overrides.scale || (view.scale === 'default' ? 'overview' : view.scale)), anchor = overrides.anchor ? { ...overrides.anchor } : { ...view.anchor };
    return { viewId: view.id, viewName: view.name, scope: copy(view.scope), anchor, scale, frame: copy(view.frame), selection: overrides.selection || null };
  }

  resolveScope(state) {
    const scope = state?.scope || DEFAULT_ATLAS_VIEW.scope, extensions = new Set(scope.extensions || DEFAULT_ATLAS_VIEW.scope.extensions), folders = scope.folders || [], excluded = scope.excludeFolders || [], tags = new Set((scope.tags || []).map(value => String(value).replace(/^#/, ''))), properties = Object.entries(scope.properties || {}), rules = (scope.rules || []).map(normalizeScopeRule), resolved = this.plugin.app.metadataCache.resolvedLinks || {}, incoming = new Map(); for (const [source, targets] of Object.entries(resolved)) for (const target of Object.keys(targets || {})) { const values = incoming.get(target) || []; values.push(source); incoming.set(target, values); } const files = this.plugin.app.vault.getFiles().filter(file => {
      if (!extensions.has(String(file.extension || '').toLowerCase())) return false;
      if (folders.length && !folders.some(folder => pathWithin(file.path, folder))) return false;
      if (excluded.some(folder => pathWithin(file.path, folder))) return false;
      const cache = this.plugin.app.metadataCache.getFileCache(file), fileTags = new Set([...(cache?.tags || []).map(value => String(value.tag || '').replace(/^#/, '')), ...Object.keys(cache?.frontmatter || {}).filter(key => key === 'tags').flatMap(() => { const value = cache?.frontmatter?.tags; return Array.isArray(value) ? value : String(value || '').split(/[ ,]+/); }).map(value => String(value).replace(/^#/, ''))]);
      if (tags.size && ![...tags].every(tag => fileTags.has(tag))) return false;
      if (!properties.every(([key, expected]) => { const actual = cache?.frontmatter?.[key]; return Array.isArray(expected) ? expected.includes(actual) : Array.isArray(actual) ? actual.includes(expected) : actual === expected; })) return false;
      const matches = rules.map(rule => { let actual = ''; if (rule.field === 'folder') actual = file.parent?.path || ''; else if (rule.field === 'path') actual = file.path; else if (rule.field === 'name') actual = file.basename; else if (rule.field === 'extension') actual = file.extension; else if (rule.field === 'tag') actual = [...fileTags]; else if (rule.field === 'property') actual = cache?.frontmatter?.[rule.key]; else if (rule.field === 'linksTo') actual = Object.keys(resolved[file.path] || {}); else if (rule.field === 'linkedFrom') actual = incoming.get(file.path) || []; else if (rule.field === 'size') actual = file.stat?.size || 0; else if (rule.field === 'created') actual = file.stat?.ctime || 0; else if (rule.field === 'modified') actual = file.stat?.mtime || 0; return compareRule(actual, rule.operator, rule.value); });
      return !matches.length || (scope.match === 'any' ? matches.some(Boolean) : matches.every(Boolean));
    });
    return { files, paths: files.map(file => file.path), signature: stableSignature(JSON.stringify([state.viewId, scope, files.map(file => [file.path, file.stat?.mtime || 0])])) };
  }

  legendFor(state) {
    const active = Object.entries(state.frame?.relationships || {}).filter(([, weight]) => Number(weight) > 0).map(([id]) => TEXT_SIGNALS[id]?.label || id), mappings = (state.frame?.visuals || []).filter(rule => rule.enabled !== false), sourceName = source => TEXT_SIGNALS[source]?.label || ({ fileSize: 'Relative file size', density: 'Local note density', relationship: 'Distinctive relationship activity', community: 'Community', links: 'Authored wikilinks' }[source] || source), common = [{ key: 'distance', label: state.anchor?.type === 'query' ? 'Distance from center' : 'Distance', meaning: state.anchor?.type === 'query' ? 'Relevance to the anchor' : active.length ? active.join(' + ') : 'Relationship field' }]; for (const mapping of mappings) { const labels = { color: 'Color', size: 'Dot size', elevation: 'Terrain', regions: 'Zones', labels: 'Labels', lines: 'Lines' }, item = { key: mapping.channel, label: labels[mapping.channel] || mapping.channel, meaning: sourceName(mapping.source) }; if (!common.some(value => value.key === item.key)) common.push(item); }
    if (state.frame?.mode === 'guided' && !common.some(item => item.key === 'beacon')) common.push({ key: 'beacon', label: 'Gravity point', meaning: 'A declared idea or pole' });
    return common;
  }

  sceneKey(state, scope, results, options) {
    const index = this.plugin.search, indexSignature = `${index.meta.length}:${index.vectors.length}:${index.meta.reduce((sum, item) => sum + Number(item.mtime || 0), 0)}`;
    return JSON.stringify([indexSignature, scope.signature, state.anchor, state.scale, state.frame, results.map(result => [result.file, Number(result.viewScore ?? result.score ?? 0)])]);
  }

  async prepareRelationshipField(state, files, roads = [], options = {}) {
    const weights = { ...(state.frame?.relationships || {}) }, profiles = new Map(), requested = new Set(Object.entries(weights).filter(([signal, weight]) => !['semantic', 'links'].includes(signal) && Number(weight) > .001).map(([signal]) => signal)); if (state.frame?.appearance?.colorBy === 'emotion') requested.add('emotion'); if (options.preloadRelationships) for (const signal of ['emotion', 'purpose', 'form']) requested.add(signal); if (options.preloadRelationships && String(state.frame?.reference || '').trim()) requested.add('position');
    for (const signal of requested) { if (signal === 'position' && !String(state.frame?.reference || '').trim()) { weights.position = 0; continue; } profiles.set(signal, await this.plugin.search.textSignalProfiles(signal, files, state.frame?.reference || '')); }
    const linkPairs = new Set((roads || []).map(road => edgeKey(road.source, road.target)));
    return { weights, profiles, linkPairs, dynamics: { ...(state.frame?.dynamics || {}), ...(state.frame?.environment || {}) }, reference: String(state.frame?.reference || '') };
  }

  applyRelationshipPresentation(state, nodes, field) {
    const colorBy = state.frame?.appearance?.colorBy || 'semantic', preferredSignal = colorBy === 'emotion' ? 'emotion' : Object.entries(field.weights || {}).filter(([signal]) => !['semantic', 'links'].includes(signal)).sort((a, b) => Number(b[1]) - Number(a[1]))[0]?.[0], signalProfiles = preferredSignal ? field.profiles.get(preferredSignal) : null, emotional = field.profiles.get('emotion');
    for (const node of nodes) {
      const profile = signalProfiles?.get(node.id), emotionProfile = emotional?.get(node.id), definitions = preferredSignal === 'emotion' ? EMOTION_LANDMARKS : [], scores = profile?.scores || {}, ranked = Object.entries(scores).sort((a, b) => Number(b[1]) - Number(a[1])), strongest = ranked[0]; node.sourceFileScale = node.fileScale; node.semanticHue = node.topicHue; node.signalIntensities = Object.fromEntries([...field.profiles].map(([signal, values]) => [signal, Math.max(0, ...Object.values(values.get(node.id)?.scores || {}).map(Number))])); node.relationshipSignal = preferredSignal || 'semantic'; node.relationshipScores = scores; node.relationshipEvidence = profile?.evidence || null; node.relationshipIntensity = strongest ? Number(strongest[1] || 0) : Number(node.uniqueness ?? node.relevance ?? .5);
      if (emotionProfile) { const weighted = EMOTION_LANDMARKS.map(item => ({ item, score: Number(emotionProfile.scores?.[`emotion:${item.key}`] || 0) ** 2 })).filter(value => value.score > .015), x = weighted.reduce((sum, value) => sum + Math.cos(value.item.hue * Math.PI / 180) * value.score, 0), y = weighted.reduce((sum, value) => sum + Math.sin(value.item.hue * Math.PI / 180) * value.score, 0); if (weighted.length) node.emotionHue = (Math.atan2(y, x) * 180 / Math.PI + 360) % 360; }
      if (colorBy === 'emotion' && Number.isFinite(node.emotionHue)) node.topicHue = node.emotionHue; else if (colorBy === 'none') node.topicHue = null; else node.topicHue = node.semanticHue;
      if (strongest) { const key = strongest[0].split(':').pop(), definition = definitions.find(item => item.key === key); node.relationshipLabel = definition?.name || key.replace(/(^|[-_])\p{L}/gu, match => match.replace(/[-_]/, '').toUpperCase()); }
      if (state.frame?.appearance?.terrain === 'intensity') node.terrainValue = node.relationshipIntensity;
    }
  }

  async applyGuidedFrame(state, nodes, layout) {
    const categories = state.frame?.mode === 'guided' ? state.frame.categories || [] : []; if (categories.length < 2 || !nodes.length) return { layout, categories: [] };
    const signal = validTextSignal(state.frame.signal), signature = stableSignature(JSON.stringify(state.frame)), scopePaths = this.resolveScope(state).paths, allFileVectors = this.plugin.search.fileVectors(), fileVectors = this.plugin.search.fileVectors(nodes.map(node => node.id)), categoryVectors = await Promise.all(categories.map(async category => { const keywords = category.keywords?.length ? ` Keywords: ${category.keywords.join(', ')}.` : '', described = await this.plugin.search.queryVector(`${category.name}. ${category.description || `Writing primarily concerned with ${category.name}.`}${keywords}`), examples = signal === 'semantic' ? (category.examples || []).map(path => allFileVectors.get(path)?.vector).filter(Boolean) : []; if (!examples.length) return described; const prototype = Float32Array.from(described, value => value * .68); for (const example of examples) for (let dimension = 0; dimension < prototype.length; dimension++) prototype[dimension] += example[dimension] * .32 / examples.length; const norm = Math.sqrt(prototype.reduce((sum, value) => sum + value * value, 0)) || 1; for (let dimension = 0; dimension < prototype.length; dimension++) prototype[dimension] /= norm; return prototype; })), anchors = categoryAnchorLayout(categories, categoryVectors, state.frame.geometry), profiles = signal === 'semantic' ? new Map() : signal === 'emotion' ? await this.plugin.search.textSignalProfiles(signal, scopePaths, state.frame.reference) : await this.plugin.search.textSignalAffinities(signal, categories, scopePaths, state.frame.reference), scoresFor = file => signal === 'semantic' ? (fileVectors.get(file)?.vector ? categoryVectors.map(categoryVector => vectorDot(fileVectors.get(file).vector, categoryVector)) : categories.map(() => 0)) : categories.map(category => Number(profiles.get(file)?.scores?.[category.id] || 0)), scoreRows = nodes.map(node => scoresFor(node.id)), calibrationRows = signal === 'semantic' ? [...this.plugin.search.fileVectors(scopePaths).values()].map(entry => categoryVectors.map(categoryVector => vectorDot(entry.vector, categoryVector))) : scopePaths.map(file => categories.map(category => Number(profiles.get(file)?.scores?.[category.id] || 0))), calibrations = categories.map((_, index) => { const values = calibrationRows.map(row => row[index]); return { low: percentile(values, .18), middle: percentile(values, .5), high: percentile(values, .88) }; }), sensitivity = clamp(state.frame.sensitivity ?? .58), categoryPull = clamp(state.frame.categoryPull ?? .78), localCohesion = clamp(state.frame.localCohesion ?? .26), unclaimedThreshold = clamp(state.frame.unclaimedThreshold ?? .34), output = new Map();
    for (let nodeIndex = 0; nodeIndex < nodes.length; nodeIndex++) {
      const node = nodes[nodeIndex], raw = scoreRows[nodeIndex], affinities = raw.map((score, index) => { const calibration = calibrations[index], spread = Math.max(.025, calibration.high - calibration.middle), relative = 1 / (1 + Math.exp(-(score - calibration.middle) / spread * (2.1 + sensitivity * 2.8))), evidence = clamp((score - calibration.low) / Math.max(.04, calibration.high - calibration.low)), absoluteConfidence = signal === 'semantic' ? 1 : .35 + clamp((score - .18) / .65) * .65; return clamp(relative * (.42 + evidence * .58) * absoluteConfidence * categories[index].weight); }), ranked = affinities.map((value, index) => ({ value, index })).sort((a, b) => b.value - a.value), natural = layout.get(node.id) || { x: 0, y: 0 }, top = anchors[ranked[0].index], unclaimed = ranked[0].value < unclaimedThreshold; let x = natural.x * localCohesion, y = natural.y * localCohesion, total = localCohesion;
      for (let index = 0; index < anchors.length; index++) { const weight = affinities[index] ** 1.65 * categoryPull; x += anchors[index].x * weight; y += anchors[index].y * weight; total += weight; } x /= Math.max(.001, total); y /= Math.max(.001, total);
      for (let iteration = 0; iteration < 52; iteration++) { let dxTotal = (natural.x - x) * localCohesion * .018, dyTotal = (natural.y - y) * localCohesion * .018; for (let index = 0; index < anchors.length; index++) { const anchor = anchors[index], affinity = affinities[index], desired = .07 + (1 - affinity) * 1.02, weight = .025 + affinity ** 2 * categoryPull, dx = anchor.x - x, dy = anchor.y - y, distance = Math.max(.015, Math.hypot(dx, dy)), correction = (distance - desired) * weight * .055; dxTotal += dx / distance * correction; dyTotal += dy / distance * correction; } x += dxTotal; y += dyTotal; }
      if (unclaimed) { x = natural.x * .72 + x * .28; y = natural.y * .72 + y * .28; } const radius = Math.hypot(x, y); if (radius > .96) { x = x / radius * .96; y = y / radius * .96; } const hueX = affinities.reduce((sum, value, index) => sum + Math.cos(anchors[index].hue * Math.PI / 180) * value ** 2, 0), hueY = affinities.reduce((sum, value, index) => sum + Math.sin(anchors[index].hue * Math.PI / 180) * value ** 2, 0);
      const colorBy = state.frame.appearance?.colorBy || 'category', hueStrength = Math.hypot(hueX, hueY) / Math.max(.001, affinities.reduce((sum, value) => sum + value ** 2, 0)); output.set(node.id, { x, y }); node.guidedFrame = true; node.guidedSignal = signal; node.guidedUnclaimed = unclaimed; node.guidedEvidence = profiles.get(node.id)?.evidence || null; node.community = unclaimed ? `guided:${signature}:unclaimed` : `guided:${signature}:${top.id}`; node.facet = node.community; node.communityLabel = unclaimed ? 'Unclaimed' : top.name; node.communityFallbackLabel = node.communityLabel; node.communityLabelConfidence = unclaimed ? 1 - ranked[0].value : ranked[0].value; node.communityMembership = unclaimed ? 1 - ranked[0].value : ranked[0].value; node.categoryHue = unclaimed || hueStrength < .08 ? null : (Math.atan2(hueY, hueX) * 180 / Math.PI + 360) % 360; if (colorBy === 'category') node.topicHue = node.categoryHue; else if (colorBy === 'none') node.topicHue = null; if (state.frame.appearance?.sizeBy === 'uniform') node.fileScale = .35; node.guidedMemberships = Object.fromEntries(categories.map((category, index) => [category.id, affinities[index]])); node.guidedAnchorWeights = node.guidedMemberships;
    }
    anchors.forEach((anchor, index) => { anchor.calibration = calibrations[index]; });
    return { layout: output, categories: anchors };
  }

  async scene(state, results = [], options = {}) {
    const scope = options.scope || this.resolveScope(state), key = this.sceneKey(state, scope, results, options), remembered = this.sceneCache.get(key); if (remembered) { this.sceneCache.delete(key); this.sceneCache.set(key, remembered); return cloneScene(await remembered); }
    const pending = state.anchor?.type === 'query' && String(state.anchor.value || '').trim() ? this.queryScene(state, scope, results, options) : state.anchor?.type === 'note' && String(state.anchor.value || '').trim() ? this.noteScene(state, scope, options) : this.vaultScene(state, scope, options);
    this.sceneCache.set(key, pending); try { const built = await pending; this.sceneCache.set(key, built); while (this.sceneCache.size > 32) this.sceneCache.delete(this.sceneCache.keys().next().value); return cloneScene(built); } catch (error) { this.sceneCache.delete(key); throw error; }
  }

  async vaultScene(state, scope, options = {}) {
    const graph = await this.plugin.search.semanticStarfield('', scope.paths), scales = options.fileScales || fileScales(this.plugin.app), nodes = graph.nodes.map(node => ({ ...node, matched: false, generation: 1, relevance: .5, fileScale: scales.get(node.id) ?? .35, facet: node.community, conceptAffinities: node.topicAffinities })), roads = manualLinks(this.plugin.app, scope.paths), field = await this.prepareRelationshipField(state, nodes.map(node => node.id), roads, options); this.applyRelationshipPresentation(state, nodes, field); const naturalLayout = new Map(nodes.map(node => [node.id, { x: Number(node.x || 0), y: Number(node.y || 0) }])), guided = await this.applyGuidedFrame(state, nodes, naturalLayout), layout = guided.layout, forceField = await this.plugin.search.relationshipForceField('', nodes, field, { vaultCenter: true });
    for (const node of nodes) { const target = layout.get(node.id); if (target) { node.layoutX = target.x; node.layoutY = target.y; } }
    const legend = this.legendFor(state); return { state, scopeSignature: scope.signature, center: { label: state.viewName, hasQuery: false, resultCount: 0, guidedCategories: guided.categories, appearance: state.frame?.appearance, dynamics: state.frame?.dynamics, forceField, legend }, nodes, edges: graph.edges || [], roads, results: [], legend, provisional: false };
  }

  async queryScene(state, scope, results, options = {}) {
    const query = String(state.anchor.value || '').trim(), showCommunities = state.frame?.appearance?.regions === true || state.frame?.appearance?.labels === true, sourceResults = results.map(result => ({ ...result })), roots = sourceResults.map(result => result.file), generations = Math.max(1, Math.min(3, Number(options.generations) || 1)), expansion = this.plugin.search.semanticGenerations(roots, generations, 5), generationByFile = new Map(expansion.nodes.map(node => [node.id, node])), allowed = new Set(scope.paths), activeFiles = expansion.nodes.map(node => node.id).filter(file => allowed.has(file)), [facets, graph] = await Promise.all([this.plugin.search.conceptFacets(query, activeFiles), this.plugin.search.semanticStarfield(query, activeFiles, activeFiles, { queryLabels: false })]);
    for (const result of sourceResults) { const facet = facets.get(result.file); result.facet = facet?.facet; result.conceptAffinities = facet?.affinities; }
    const byFile = new Map(sourceResults.map(result => [result.file, result])), scales = options.fileScales || fileScales(this.plugin.app), rankingScores = sourceResults.map(result => Number(result.viewScore ?? result.score ?? 0)), rankingLow = rankingScores.length ? Math.min(...rankingScores) : 0, rankingHigh = rankingScores.length ? Math.max(...rankingScores) : 1, rankingSpread = Math.max(.001, rankingHigh - rankingLow), semanticScores = graph.nodes.map(node => Number(node.semanticScore || 0)), semanticLow = semanticScores.length ? Math.min(...semanticScores) : 0, semanticHigh = semanticScores.length ? Math.max(...semanticScores) : 1, semanticSpread = Math.max(.001, semanticHigh - semanticLow), expansionEdges = expansion.edges.map(edge => ({ ...edge, residualScore: 0 })), edgeKeys = new Set((graph.edges || []).map(edge => edgeKey(edge.source, edge.target))), combinedEdges = [...(graph.edges || []), ...expansionEdges.filter(edge => !edgeKeys.has(edgeKey(edge.source, edge.target)))];
    const nodes = graph.nodes.map(node => { const result = byFile.get(node.id), generation = generationByFile.get(node.id), subtopic = facets.get(node.id), semanticRelevance = (Number(node.semanticScore || 0) - semanticLow) / semanticSpread, rankedRelevance = result ? (Number(result.viewScore ?? result.score ?? 0) - rankingLow) / rankingSpread : 0, expandedRelevance = generation && generation.generation > 1 ? Math.max(.22, Math.min(.62, Number(generation.relationScore || 0))) : semanticRelevance, community = showCommunities && subtopic ? subtopic.facet : node.community, membership = subtopic ? Number(subtopic.affinities?.[subtopic.facet] || 0) : Number(node.communityMembership || 0); return { ...node, generation: generation?.generation || 1, parent: generation?.parent || null, matched: Boolean(generation), relevance: result ? .08 + rankedRelevance * .92 : expandedRelevance, fileScale: scales.get(node.id) ?? .35, facet: subtopic?.facet ?? result?.facet ?? node.community, community, communityMembership: showCommunities ? membership : node.communityMembership, communityLabel: showCommunities ? subtopic?.label || '' : node.communityLabel, communityFallbackLabel: showCommunities ? subtopic?.fallbackLabel || '' : node.communityFallbackLabel, communityLabelConfidence: showCommunities ? Number(subtopic?.confidence || 0) : node.communityLabelConfidence, conceptAffinities: subtopic?.affinities || result?.conceptAffinities || node.topicAffinities, topicAffinities: showCommunities && subtopic ? subtopic.affinities : node.topicAffinities, contextScore: result?.contextScore }; }), roads = manualLinks(this.plugin.app, nodes.map(node => node.id)), field = await this.prepareRelationshipField(state, nodes.map(node => node.id), roads, options); this.applyRelationshipPresentation(state, nodes, field); const naturalLayout = new Map(nodes.map(node => [node.id, { x: Number(node.x || 0), y: Number(node.y || 0) }])), guided = await this.applyGuidedFrame(state, nodes, naturalLayout), layout = guided.layout, forceField = await this.plugin.search.relationshipForceField(query, nodes, field);
    for (const node of nodes) { const target = layout.get(node.id); if (target) { node.layoutX = target.x; node.layoutY = target.y; } }
    const legend = this.legendFor(state); return { state, scopeSignature: scope.signature, center: { label: query, hasQuery: true, resultCount: sourceResults.length, guidedCategories: guided.categories, appearance: state.frame?.appearance, dynamics: state.frame?.dynamics, forceField, legend }, nodes, edges: combinedEdges, roads, results: sourceResults, legend, provisional: false };
  }

  async noteScene(state, scope, options = {}) {
    const filePath = String(state.anchor.value || ''), showCommunities = state.frame?.appearance?.regions === true || state.frame?.appearance?.labels === true, limit = state.scale === 'detail' ? 32 : state.scale === 'neighborhood' ? 22 : 16, graph = this.plugin.search.semanticNeighbors(filePath, limit), allowed = new Set(scope.paths); let nodes = graph.nodes.filter(node => allowed.has(node.id)).map(node => ({ ...node, semanticScore: Number(node.score || 0) })), edges = (graph.edges || []).filter(edge => allowed.has(edge.source) && allowed.has(edge.target));
    if (showCommunities) { const facets = await this.plugin.search.conceptFacetsFromFile(filePath, nodes.map(node => node.id)); nodes = nodes.map(node => ({ ...node, facet: facets.get(node.id)?.facet, community: facets.get(node.id)?.facet || node.community, communityLabel: facets.get(node.id)?.label || '', conceptAffinities: facets.get(node.id)?.affinities, topicAffinities: facets.get(node.id)?.affinities || node.topicAffinities })); }
    const scores = nodes.map(node => Number(node.score || 0)), low = scores.length ? Math.min(...scores) : 0, high = scores.length ? Math.max(...scores) : 1, spread = Math.max(.001, high - low), scales = options.fileScales || fileScales(this.plugin.app); nodes = nodes.map(node => ({ ...node, relevance: (Number(node.score || 0) - low) / spread, matched: true, generation: 1, fileScale: scales.get(node.id) ?? .35 })); const roads = manualLinks(this.plugin.app, [filePath, ...nodes.map(node => node.id)]), field = await this.prepareRelationshipField(state, nodes.map(node => node.id), roads, options); this.applyRelationshipPresentation(state, nodes, field); const naturalLayout = new Map(nodes.map(node => [node.id, { x: Number(node.x || 0), y: Number(node.y || 0) }])), guided = await this.applyGuidedFrame(state, nodes, naturalLayout), layout = guided.layout, forceField = await this.plugin.search.relationshipForceField('', nodes, field, { centerFile: filePath });
    for (const node of nodes) { const target = layout.get(node.id); if (target) { node.layoutX = target.x; node.layoutY = target.y; } }
    const legend = this.legendFor(state); return { state, scopeSignature: scope.signature, center: { id: filePath, label: basename(filePath), hasQuery: true, resultCount: nodes.length, guidedCategories: guided.categories, appearance: state.frame?.appearance, dynamics: state.frame?.dynamics, forceField, legend }, nodes, edges, roads, results: nodes, legend, provisional: false };
  }

  provisionalScene(state, baseScene, results, positions = new Map()) {
    const scores = results.map(result => Number(result.viewScore ?? result.score ?? 0)), low = scores.length ? Math.min(...scores) : 0, high = scores.length ? Math.max(...scores) : 1, spread = Math.max(.001, high - low), byFile = new Map(results.map(result => [result.file, result])), nodes = baseScene.nodes.map(base => { const result = byFile.get(base.id), current = positions.get(base.id), positioned = current ? { layoutX: current.x, layoutY: current.y } : {}; return result ? { ...base, ...positioned, matched: true, generation: 1, relevance: .08 + (Number(result.viewScore ?? result.score ?? 0) - low) / spread * .92 } : { ...base, ...positioned, matched: false, relevance: 0 }; });
    const legend = this.legendFor(state); return { state, scopeSignature: baseScene.scopeSignature, center: { label: state.anchor.value, hasQuery: true, resultCount: results.length, transition: 'provisional', guidedCategories: baseScene.center?.guidedCategories || [], appearance: state.frame?.appearance, dynamics: state.frame?.dynamics, forceField: baseScene.center?.forceField || null, legend }, nodes, edges: baseScene.edges, roads: baseScene.roads, results, legend, provisional: true };
  }

  clear() { this.sceneCache.clear(); }
}
